import { achievements, animals, shopItems } from './gameData';
import type { InventoryItem, Mood, Pet, SaveData, Stats, TimeOfDay, Weather } from './types';

export const clamp = (value: number, min = 0, max = 100) => Math.min(max, Math.max(min, Number.isFinite(value) ? value : min));
export const todayKey = () => new Date().toLocaleDateString('en-CA');
export const xpNeed = (level: number) => Math.min(100, 45 + level * 5);
export const getEvolution = (level: number) => level >= 30 ? 'Adult' : level >= 15 ? 'Teen' : level >= 5 ? 'Kid' : 'Baby';
export const getAnimal = (id: string) => animals.find((a) => a.id === id) ?? animals[0]!;
export const randomWeather = (): Weather => (['Sunny','Rainy','Cloudy','Snowy','Windy'] as Weather[])[Math.floor(Math.random()*5)] ?? 'Sunny';
export const getTimeOfDay = (): TimeOfDay => { const h = new Date().getHours(); return h < 11 ? 'Morning' : h < 16 ? 'Afternoon' : h < 20 ? 'Evening' : 'Night'; };
export const newPet = (animalId: string, customName: string): Pet => ({ id: crypto.randomUUID(), animalId, customName: customName.trim() || getAnimal(animalId).species, level: 1, birthDate: Date.now(), stats: { hunger: 82, happiness: 82, energy: 84, cleanliness: 84, health: 90, affection: 20, xp: 0 }, isSleeping: false, equippedHabitat: 'hab-0', equippedDecorations: [], actionCounts: {}, snackCountToday: 0, lastSnackDate: todayKey(), sickMinutes: 0 });
export const defaultSave = (): SaveData => ({ userCoins: 160, activePetId: null, pets: [], inventory: [{ itemId:'hab-0', quantity:1, equipped:true }], achievements: [], unlockedAnimals: ['cat','dog','rabbit'], settings: { sound: true, reducedMotion: false, theme: 'Green Retro' }, dailyReward: { lastClaimDate: null, streak: 0 }, lastUpdatedAt: Date.now(), weather: randomWeather(), weatherUpdatedAt: Date.now() });
export const normalizeStats = (stats: Partial<Stats> | undefined): Stats => ({ hunger: clamp(stats?.hunger ?? 80), happiness: clamp(stats?.happiness ?? 80), energy: clamp(stats?.energy ?? 80), cleanliness: clamp(stats?.cleanliness ?? 80), health: clamp(stats?.health ?? 90), affection: clamp(stats?.affection ?? 10), xp: clamp(stats?.xp ?? 0) });
export const getMood = (pet: Pet): Mood => { const s = normalizeStats(pet.stats); if (pet.isSleeping) return 'Tidur'; if (s.health <= 0) return 'Very Sick'; if (s.health < 35) return 'Sakit'; if (s.energy < 25) return 'Ngantuk'; if (s.hunger < 25) return 'Lapar'; if (s.cleanliness < 25) return 'Kotor'; if (s.happiness < 20) return 'Sedih'; if (s.happiness < 45) return 'Bosan'; if (s.affection > 80 && s.happiness > 75) return 'Manja'; return 'Senang'; };
export const addInventory = (inventory: InventoryItem[], itemId: string, qty = 1) => { const found = inventory.find((i) => i.itemId === itemId); return found ? inventory.map((i) => i.itemId === itemId ? { ...i, quantity: i.quantity + qty } : i) : [...inventory, { itemId, quantity: qty }]; };
export const applyStats = (pet: Pet, delta: Partial<Stats>) => ({ ...pet, stats: normalizeStats({ ...pet.stats, hunger: pet.stats.hunger + (delta.hunger ?? 0), happiness: pet.stats.happiness + (delta.happiness ?? 0), energy: pet.stats.energy + (delta.energy ?? 0), cleanliness: pet.stats.cleanliness + (delta.cleanliness ?? 0), health: pet.stats.health + (delta.health ?? 0), affection: pet.stats.affection + (delta.affection ?? 0), xp: pet.stats.xp + (delta.xp ?? 0) }) });
export function levelPet(pet: Pet): { pet: Pet; gained: number } { let next = { ...pet, stats: { ...pet.stats } }; let gained = 0; while (next.level < 50 && next.stats.xp >= xpNeed(next.level)) { next.stats.xp = clamp(next.stats.xp - xpNeed(next.level)); next.level += 1; gained += 1; } return { pet: next, gained }; }
export const withOfflineProgress = (save: SaveData): SaveData => { const minutes = Math.min(480, Math.max(0, Math.floor((Date.now() - (save.lastUpdatedAt || Date.now())) / 60000))); if (!minutes) return save; const pets = save.pets.map((p) => { const bad = p.stats.hunger < 20 || p.stats.cleanliness < 20 || p.stats.energy < 15; return applyStats({ ...p, sickMinutes: bad ? p.sickMinutes + minutes : 0 }, { hunger: -minutes*0.08, happiness: -minutes*0.03, cleanliness: -minutes*0.04, energy: p.isSleeping ? minutes*0.18 : -minutes*0.02, health: bad ? -minutes*0.05 : 0 }); }); return { ...save, pets, lastUpdatedAt: Date.now(), weather: Date.now() - save.weatherUpdatedAt > 180000 ? randomWeather() : save.weather, weatherUpdatedAt: Date.now() - save.weatherUpdatedAt > 180000 ? Date.now() : save.weatherUpdatedAt }; };
export const safeParseSave = (raw: string | null): SaveData => { if (!raw) return defaultSave(); try { const parsed = JSON.parse(raw) as Partial<SaveData>; const base = defaultSave(); return withOfflineProgress({ ...base, ...parsed, pets: Array.isArray(parsed.pets) ? parsed.pets.map((p) => ({ ...newPet(p.animalId || 'cat', p.customName || 'Pal'), ...p, stats: normalizeStats(p.stats), equippedDecorations: p.equippedDecorations ?? [], actionCounts: p.actionCounts ?? {} })) : [], inventory: Array.isArray(parsed.inventory) ? parsed.inventory : [], achievements: Array.isArray(parsed.achievements) ? parsed.achievements : [], unlockedAnimals: Array.isArray(parsed.unlockedAnimals) ? parsed.unlockedAnimals : base.unlockedAnimals, settings: { ...base.settings, ...(parsed.settings ?? {}) }, dailyReward: { ...base.dailyReward, ...(parsed.dailyReward ?? {}) }, lastUpdatedAt: parsed.lastUpdatedAt ?? Date.now(), weather: parsed.weather ?? randomWeather(), weatherUpdatedAt: parsed.weatherUpdatedAt ?? Date.now() }); } catch { return defaultSave(); } };
export const getUnlockedAchievements = (save: SaveData): string[] => { const pet = save.pets.find((p) => p.id === save.activePetId); const stats = pet?.stats; const checks: Record<string, boolean> = { 'first-meal': (pet?.actionCounts.feed ?? 0) >= 1, 'clean-10': (pet?.actionCounts.clean ?? 0) >= 10, 'play-10': (pet?.actionCounts.play ?? 0) >= 10, 'sleep-5': (pet?.actionCounts.sleep ?? 0) >= 5, 'healthy-hero': (pet?.actionCounts.medicine ?? 0) >= 1 && (stats?.health ?? 0) > 70, 'level-10': (pet?.level ?? 0) >= 10, 'level-25': (pet?.level ?? 0) >= 25, 'level-50': (pet?.level ?? 0) >= 50, 'rich-keeper': save.userCoins >= 1000, 'collector-5': save.pets.length >= 5, 'perfect-day': !!stats && Object.entries(stats).filter(([k]) => k !== 'xp').every(([,v]) => v > 90), 'best-friend': (stats?.affection ?? 0) >= 100 };
  return achievements.filter((a) => checks[a.id] && !save.achievements.includes(a.id)).map((a) => a.id); };
export const itemById = (id: string) => shopItems.find((i) => i.id === id);
