export const GAME_VERSION = '1.0.0';
export const GAME_VERSION_LABEL = 'Beta';
export const GAME_BUILD_DATE = '2026-05-11';
export const GAME_NAME = 'Pixel Paws';

export const CHANGELOG = [
  { version: '1.0.0 Beta', date: '2026-05-11', title: 'Pixel Paws Beta Launch', changes: ['Unlocked every previously disabled Mini Games Hub card with real gameplay that matches the title.', 'Added playable Pet Puzzle Slide, Reaction Tap, Coin Rain, Jump Rope, Tiny Racing, and Pet Dance Timing instead of Coming Soon buttons.', 'Kept all 20 mini games behind the shared start screen, pause/exit controls, result screen, and one-reward-per-run safety.', 'Updated News, changelog, and version badge to v1.0.0 Beta.', 'Refreshed Remote Config defaults for the Beta Launch announcement and global event labels.', 'Improved the hub so no active card points to fake tap-only gameplay.'] },
  { version: '0.5.0', date: '2026-05-11', title: 'Real Mini Games & PWA Update', changes: ['Rebuilt active mini games so each one matches its title instead of random tapping.', 'Added real card matching, food catching, runner jumping, bubble popping, treasure digging, fishing, fruit sorting, rhythm timing, maze movement, bug whacking, pattern memory, cleaning, snack stacking, and star catching loops.', 'Disabled unfinished mini games with clear Coming Soon reasons instead of fake play buttons.', 'Tutorial highlight now starts after the user taps Mulai Adopt/adopts a first pet.', 'Added Android/iPhone PWA manifest metadata for installable standalone play.', 'Expanded trait options with Lazy and Clingy and kept migration compatibility.'] },
  { version: '0.4.0', date: '2026-05-11', title: 'Major Gameplay, Quests, Offline & Global Updates', changes: ['Added interactive onboarding tutorial with saved progress and completion reward.', 'Added Help / Guidebook, Quest Board, Mailbox, Notification Center, and Room Decoration pages.', 'Expanded daily goals and weekly quests with safe one-time claim buttons.', 'Added save schema defaults for profile showcase, mail, notifications, room decor, album, and player rank.', 'Fixed offline fallback buttons so Retry and Offline Help work while Wi-Fi is disconnected.', 'Allowed notification setup to create a local device token for guests and sync it when signed in.', 'Synced shop inventory items into Feed, Snack, Medicine, and Play action pickers.', 'Fixed global shop discounts from remote tuning so discounts apply even outside weekly events.'] },
  { version: '0.3.0', date: '2026-05-10', title: 'Couple Mode & Guest Trial', changes: ['Added invite code rooms.', 'Added guest trial.', 'Improved pet care actions.', 'Improved mobile layout.'] },
  { version: '0.2.0', date: '2026-05-01', title: 'Care Update', changes: ['Added detailed care options.', 'Expanded shop items.', 'Improved save import/export.'] },
] as const;

export const ANNOUNCEMENTS = [
  { id: 'beta-launch-1-0-0', title: 'Pixel Paws v1.0.0 Beta is Live!', message: 'All Mini Games Hub cards are now playable with title-matching gameplay, safer rewards, and the Beta Launch label.', type: 'info', active: true, version: '1.0.0' },
  { id: 'all-mini-games-ready-1-0-0', title: 'All 20 mini games are ready', message: 'Pet Puzzle Slide, Reaction Tap, Coin Rain, Jump Rope, Tiny Racing, and Pet Dance Timing graduated from disabled to fully playable.', type: 'info', active: true, version: '1.0.0' },
  { id: 'daily-news-beta-games-1-0-0', title: 'Today in Pixel Paws: Arcade day', message: 'Try a puzzle, race lanes, catch coin rain, jump rope, then finish with a pet dance combo for extra arcade vibes.', type: 'info', active: true, version: '1.0.0' },
  { id: 'festival-season-news-1-0-0', title: 'Seasonal celebrations are rotating', message: 'Event news now uses the global event label from tuning when available, while local news keeps Beta Launch updates visible.', type: 'info', active: true, version: '1.0.0' },
  { id: 'real-mini-games-pwa-0-5-0', title: 'Today: v0.5.0 real mini games + PWA', message: 'Mini games now use title-matching gameplay, unfinished games are disabled instead of fake, tutorial highlight starts after adoption, and Pixel Paws has Android/iPhone PWA metadata.', type: 'info', active: true, version: '0.5.0' },
  { id: 'major-gameplay-0-4-0', title: 'Today: Major gameplay expansion', message: 'Tutorial, Guidebook, Quest Board, Mailbox, Notification Center, Room Decor, expanded daily goals, and weekly quests are now available.', type: 'info', active: true, version: '0.4.0' },
  { id: 'offline-help-fcm-0-4-0', title: 'Today: Offline help and notification fixes', message: 'Offline Retry and Help now work from the cached fallback page, and notification setup can create a local token before cloud sync.', type: 'info', active: true, version: '0.4.0' },
  { id: 'shop-action-sync-0-4-0', title: 'Today: Shop items now match actions', message: 'Food, snacks, medicine, and toys bought in Shop now show up in the matching care action pickers and Inventory use flow.', type: 'info', active: true, version: '0.4.0' },
  { id: 'offline-global-tuning-0-4-0', title: 'Today: Offline fallback and global tuning', message: 'Refreshes while offline can show the Pixel Paws offline page after one online visit, and global shop discounts now apply from tuning config.', type: 'info', active: true, version: '0.4.0' },
  { id: 'welcome-0-3-0', title: 'Welcome to Pixel Paws!', message: 'Invite a friend and care for your pet together.', type: 'info', active: true, version: '0.3.0' },
  { id: 'guest-trial-0-3-0', title: 'Guest Trial', message: 'Guest mode now gives five minutes to try the game before upgrading.', type: 'warning', active: true, version: '0.3.0' },
] as const;
