'use client';

import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import CoupleModePage from '@/src/components/couple/CoupleModePage';
import LoginPage from '@/src/components/LoginPage';
import GuestTrialBadge from '@/src/components/auth/GuestTrialBadge';
import TrialExpiredGate from '@/src/components/auth/TrialExpiredGate';
import { useAuth } from '@/src/hooks/useAuth';
import { isFirebaseConfigured } from '@/src/lib/firebase';
import { achievements, animals, dialogs, shopItems } from '@/lib/gameData';
import { addInventory, applyStats, clamp, defaultSave, getAnimal, getEvolution, getMood, getTimeOfDay, getUnlockedAchievements, itemById, levelPet, newPet, randomWeather, safeParseSave, todayKey, xpNeed } from '@/lib/gameLogic';
import { careOptionsByAction } from '@/src/data/careOptions';
import { applyCareOption, optionDisabledReason } from '@/src/lib/actionResolver';
import type { Animal, InventoryItem, ItemCategory, Mood, Pet, SaveData, ShopItem, Stats, ThemeName, Toast } from '@/lib/types';
import type { CareAction, CareOption, PetAnimationType } from '@/src/types/care';
import { GUEST_SAVE_CACHE_KEY } from '@/src/lib/guestTrial';

const SAVE_KEY = 'pixel-pals-save-v1';
const LOG_KEY = 'pixel-paws-activity-log';
const TUTORIAL_KEY = 'pixel-paws-tutorial-seen';
const navItems = ['Pet', 'Shop', 'Inventory', 'Games', 'Couple', 'Achievements', 'Dex', 'Settings'];
const actionCards: Array<{ key: CareAction; label: string; icon: string; description: string }> = [
  { key: 'feed', label: 'Feed', icon: '🍽️', description: 'Pilih makanan utama.' },
  { key: 'snack', label: 'Snack', icon: '🍬', description: 'Camilan bahagia.' },
  { key: 'play', label: 'Play', icon: '🎾', description: 'Pilih permainan.' },
  { key: 'clean', label: 'Clean', icon: '🧼', description: 'Bersihkan pet.' },
  { key: 'medicine', label: 'Medicine', icon: '💊', description: 'Rawat kesehatan.' },
  { key: 'pet', label: 'Pet', icon: '💖', description: 'Interaksi kasih sayang.' },
  { key: 'walk', label: 'Walk', icon: '🚶', description: 'Pilih lokasi jalan.' },
  { key: 'train', label: 'Train', icon: '🏋️', description: 'Latihan XP.' },
  { key: 'sleep', label: 'Sleep', icon: '💤', description: 'Istirahat.' },
  { key: 'wake', label: 'Wake Up', icon: '☀️', description: 'Bangunkan pelan.' },
];

type ShopTab = ItemCategory | 'Snacks' | 'Medicine' | 'Special';
type ShopCatalogItem = { id: string; name: string; category: ShopTab; price: number; emoji: string; description: string; effect: string; source: 'shop' | 'care'; careOption?: CareOption; statEffects?: Partial<Stats> };

function PixelButton({ children, onClick, disabled, tone = 'bg-[var(--accent)]', type = 'button' }: { children: React.ReactNode; onClick?: () => void; disabled?: boolean; tone?: string; type?: 'button' | 'submit' }) {
  return <button type={type} onClick={onClick} disabled={disabled} className={`pixel-border-sm ${tone} w-full px-3 py-2 text-[10px] leading-relaxed text-slate-950 transition active:translate-x-1 active:translate-y-1 active:shadow-none disabled:cursor-not-allowed disabled:opacity-50 sm:w-auto`}>{children}</button>;
}
function PixelCard({ children, className = '' }: { children: React.ReactNode; className?: string }) { return <section className={`pixel-border min-w-0 max-w-full overflow-hidden break-words bg-[var(--panel)] p-3 sm:p-4 ${className}`}>{children}</section>; }
function StatBar({ label, value, color }: { label: string; value: number; color: string }) {
  const safe = clamp(value);
  const width = `${safe}%`;
  return (
    <div>
      <div className="mb-1 flex justify-between text-[9px]"><span>{label}</span><span>{Math.round(safe)}/100</span></div>
      <div className="h-4 border-2 border-slate-950 bg-white"><div className={`h-full ${color}`} style={{ width }} /></div>
    </div>
  );
}
function ToastProvider({ toasts }: { toasts: Toast[] }) { return <div className="fixed right-3 top-3 z-50 space-y-2">{toasts.slice(-4).map((t) => <div key={t.id} className="pixel-border-sm animate-pop bg-white p-3 text-[10px]">{t.message}</div>)}</div>; }
function ConfirmModal({ title, body, onCancel, onConfirm }: { title: string; body: string; onCancel: () => void; onConfirm: () => void }) { return <div className="fixed inset-0 z-40 grid place-items-end bg-black/50 p-0 sm:place-items-center sm:p-4"><PixelCard className="max-h-[85vh] w-full overflow-y-auto rounded-t-2xl sm:w-[calc(100vw-24px)] sm:max-w-md sm:rounded-none"><h2 className="mb-3 text-sm">{title}</h2><p className="mb-4 text-[10px] leading-relaxed">{body}</p><div className="flex flex-col gap-2 sm:flex-row"><PixelButton onClick={onConfirm} tone="bg-red-300">Ya</PixelButton><PixelButton onClick={onCancel} tone="bg-white">Batal</PixelButton></div></PixelCard></div>; }

function PixelSceneDecor({ habitat, weather, time, animation }: { habitat: string; weather: string; time: string; animation: PetAnimationType }) {
  const night = time === 'Night';
  return <div className={`pointer-events-none absolute inset-0 overflow-hidden ${night ? 'bg-indigo-950/20' : ''}`}>
    <div className="absolute left-3 top-3 text-2xl">{night ? '🌙' : weather === 'Snowy' ? '☃️' : '☀️'}</div>
    <div className="absolute right-4 top-4 text-xl">{habitat.includes('Forest') ? '🌲' : habitat.includes('Beach') ? '🌊' : habitat.includes('Snow') ? '❄️' : habitat.includes('Aquarium') ? '🫧' : '🪟'}</div>
    <div className="absolute bottom-0 left-0 right-0 h-8 border-t-4 border-slate-950 bg-green-300/70">{habitat.includes('Beach') ? '〰〰〰〰' : habitat.includes('Aquarium') ? '≈≈≈≈≈' : '▰ ▰ ✿ ▰ ▰'}</div>
    {weather === 'Rainy' && <div className="animate-rain-pixel absolute inset-x-0 top-0 text-cyan-700">╱ ╱ ╱ ╱ ╱ ╱ ╱</div>}
    {weather === 'Snowy' && <div className="animate-sparkle-float absolute inset-x-0 top-8 text-white">✦ ✧ ✦ ✧ ✦</div>}
    {animation !== 'idle' && <div className="animate-sparkle-float absolute left-1/2 top-8 text-2xl">{animation === 'buyItem' ? '🪙' : animation === 'clean' ? '🫧' : animation === 'medicine' ? '✚' : animation === 'walk' ? '🐾' : '✨'}</div>}
  </div>;
}
function PetSprite({ pet, mood, animation, reduced }: { pet: Pet; mood: Mood; animation: PetAnimationType; reduced: boolean }) {
  const animal = getAnimal(pet.animalId); const evo = getEvolution(pet.level); const size = evo === 'Adult' ? 'text-6xl sm:text-8xl' : evo === 'Teen' ? 'text-5xl sm:text-7xl' : evo === 'Kid' ? 'text-5xl sm:text-6xl' : 'text-4xl sm:text-5xl';
  const anim = reduced ? '' : animation === 'eat' || animation === 'snack' ? 'animate-eat' : animation === 'walk' || animation === 'play' || animation === 'train' ? 'animate-walk-pixel' : mood === 'Sakit' || mood === 'Very Sick' ? 'animate-sick' : mood === 'Senang' || mood === 'Manja' ? 'animate-happy' : 'animate-idle';
  return <div className={`relative z-10 mx-auto flex h-40 w-40 max-w-full sm:h-48 sm:w-48 items-center justify-center border-4 border-slate-950 bg-white ${anim}`} style={{ background: `linear-gradient(135deg, ${animal.color}, white)` }}><div className={`${size} drop-shadow`}><span>{animal.emoji}</span><span className="block text-center text-xs">{animal.expressions[mood] ?? '^_^'}</span>{pet.equippedAccessory && <span className="block text-center text-2xl">{itemById(pet.equippedAccessory)?.emoji}</span>}</div></div>;
}
function PetDialog({ text }: { text: string }) { return <div className="pixel-border-sm mt-3 bg-white p-3 text-[10px] leading-relaxed">💬 {text}</div>; }

export default function PixelPalsApp() {
  const [save, setSave] = useState<SaveData>(defaultSave());
  const [loaded, setLoaded] = useState(false);
  const [page, setPage] = useState('Pet');
  const [dialog, setDialog] = useState('Hi keeper! Buka tutorial kalau bingung ya.');
  const [toasts, setToasts] = useState<Toast[]>([]);
  const [dailyOpen, setDailyOpen] = useState(false);
  const [confirm, setConfirm] = useState<null | 'pet' | 'all'>(null);
  const [selectedAnimal, setSelectedAnimal] = useState('cat');
  const [petName, setPetName] = useState('');
  const [activeAction, setActiveAction] = useState<CareAction | null>(null);
  const [activeAnimation, setActiveAnimation] = useState<PetAnimationType>('idle');
  const [logs, setLogs] = useState<string[]>([]);
  const [tutorialOpen, setTutorialOpen] = useState(false);
  const [shopTab, setShopTab] = useState<ShopTab>('Food');
  const [shopQuery, setShopQuery] = useState('');
  const [shopDetail, setShopDetail] = useState<ShopCatalogItem | null>(null);
  const [game, setGame] = useState<'none'|'catch'|'memory'|'rhythm'>('none');
  const animationTimer = useRef<number | null>(null);
  const auth = useAuth();

  const activePet = useMemo(() => save.pets.find((p) => p.id === save.activePetId) ?? null, [save.pets, save.activePetId]);
  const mood = activePet ? getMood(activePet) : 'Senang';
  const themeClass = `theme-${save.settings.theme.replaceAll(' ', '-')}`;
  const timeOfDay = loaded ? getTimeOfDay() : 'Morning';
  const dailyReady = save.dailyReward.lastClaimDate !== todayKey();

  const notify = useCallback((message: string, type: Toast['type'] = 'info') => { const id = crypto.randomUUID(); setToasts((t) => [...t.slice(-3), { id, message, type }]); window.setTimeout(() => setToasts((t) => t.filter((x) => x.id !== id)), 2600); }, []);
  const pushLog = useCallback((entry: string) => setLogs((prev) => [`${new Date().toLocaleTimeString([], { hour:'2-digit', minute:'2-digit' })} · ${entry}`, ...prev].slice(0, 30)), []);
  const triggerAnimation = useCallback((type: PetAnimationType) => { if (animationTimer.current) window.clearTimeout(animationTimer.current); setActiveAnimation(type); animationTimer.current = window.setTimeout(() => setActiveAnimation('idle'), type === 'levelUp' ? 1800 : 1300); }, []);
  const updateSave = useCallback((fn: (s: SaveData) => SaveData) => setSave((prev) => ({ ...fn(prev), lastUpdatedAt: Date.now() })), []);
  const updateActivePet = useCallback((fn: (p: Pet) => Pet) => updateSave((s) => ({ ...s, pets: s.pets.map((p) => p.id === s.activePetId ? fn(p) : p) })), [updateSave]);
  const requireTrialAccess = useCallback((message = 'Login to continue playing.') => { if (!auth.isGuest || !auth.isGuestTrialExpired) return true; notify(message, 'warning'); void auth.markGuestTrialExpired(); return false; }, [auth, notify]);

  useEffect(() => { setSave(safeParseSave(window.localStorage.getItem(SAVE_KEY))); setLogs(JSON.parse(window.localStorage.getItem(LOG_KEY) || '[]') as string[]); setTutorialOpen(window.localStorage.getItem(TUTORIAL_KEY) !== 'yes'); setLoaded(true); }, []);
  useEffect(() => { if (loaded) window.localStorage.setItem(SAVE_KEY, JSON.stringify(save)); }, [loaded, save]);
  useEffect(() => { if (loaded && auth.isGuest) window.localStorage.setItem(GUEST_SAVE_CACHE_KEY, JSON.stringify(save)); }, [auth.isGuest, loaded, save]);
  useEffect(() => { if (auth.isGuest && !auth.isGuestTrialExpired && auth.guestTrialRemainingMs <= 0) void auth.markGuestTrialExpired(); }, [auth]);
  useEffect(() => { if (loaded) window.localStorage.setItem(LOG_KEY, JSON.stringify(logs)); }, [loaded, logs]);
  useEffect(() => { return () => { if (animationTimer.current) window.clearTimeout(animationTimer.current); }; }, []);
  useEffect(() => { if (!loaded || auth.isGuestTrialExpired) return; const id = window.setInterval(() => updateSave((s) => ({ ...s, pets: s.pets.map((p) => applyStats(p, { hunger:-0.22, happiness:-0.08, cleanliness:-0.09, energy:p.isSleeping ? 0.7 : -0.04, health:p.stats.hunger < 15 || p.stats.cleanliness < 15 ? -0.15 : 0 })), weather: Date.now() - s.weatherUpdatedAt > 180000 ? randomWeather() : s.weather, weatherUpdatedAt: Date.now() - s.weatherUpdatedAt > 180000 ? Date.now() : s.weatherUpdatedAt })), 8000); return () => window.clearInterval(id); }, [auth.isGuestTrialExpired, loaded, updateSave]);
  useEffect(() => { if (!activePet) return; const list = dialogs[mood] ?? dialogs.Senang; const id = window.setInterval(() => setDialog(list[Math.floor(Math.random() * list.length)] ?? 'Bip bop!'), 5000); return () => window.clearInterval(id); }, [activePet, mood]);
  useEffect(() => { if (!loaded || auth.isGuestTrialExpired) return; const newly = getUnlockedAchievements(save); if (!newly.length) return; setSave((s) => ({ ...s, achievements: [...s.achievements, ...newly], userCoins: s.userCoins + newly.reduce((sum, id) => sum + (achievements.find((a) => a.id === id)?.reward ?? 0), 0) })); newly.forEach((id) => notify(`Achievement unlocked! ${achievements.find((a) => a.id === id)?.title ?? id}`, 'success')); }, [auth.isGuestTrialExpired, loaded, save, notify]);

  const adopt = (animalId = selectedAnimal, name = petName) => { if (!requireTrialAccess()) return; const pet = newPet(animalId, name || getAnimal(animalId).species); updateSave((s) => ({ ...s, pets: [...s.pets, pet], activePetId: pet.id, unlockedAnimals: Array.from(new Set([...s.unlockedAnimals, animalId])) })); setPage('Pet'); notify('Pet adopted!', 'success'); pushLog(`Adopted ${pet.customName}.`); };
  const performCare = (option: CareOption) => { if (!requireTrialAccess()) return; if (!activePet) return; const resolved = applyCareOption(activePet, option, save.inventory, save.userCoins); if (!resolved.result.ok) { notify(resolved.result.reason ?? 'Action unavailable', 'warning'); return; } updateSave((s) => ({ ...s, userCoins: resolved.coins, inventory: resolved.inventory, pets: s.pets.map((p) => p.id === activePet.id ? resolved.pet : p) })); setDialog(resolved.result.dialog); notify(resolved.result.toast, 'success'); pushLog(resolved.result.log); triggerAnimation(resolved.result.levelUp ? 'levelUp' : resolved.result.petAnimation); setActiveAction(null); if (resolved.result.levelUp) notify('Level up!', 'success'); };

  const shopCatalog = useMemo<ShopCatalogItem[]>(() => {
    const base = shopItems.map((item) => ({ id:item.id, name:item.name, category:item.category as ShopTab, price:item.price, emoji:item.emoji, description:item.description, effect:item.effect, source:'shop' as const, statEffects:item.statEffects }));
    const care = [...careOptionsByAction.feed, ...careOptionsByAction.snack, ...careOptionsByAction.medicine].filter((o) => !o.isFreeDaily).map((o) => { const existingId = o.itemName ? shopItems.find((item) => item.name === o.itemName)?.id : undefined; const id = existingId ?? o.id; return { id, name:o.name, category:o.action === 'snack' ? 'Snacks' as ShopTab : o.action === 'medicine' ? 'Medicine' as ShopTab : 'Food' as ShopTab, price:o.coinCost ?? (o.rarity === 'Legendary' ? 140 : o.rarity === 'Epic' ? 95 : o.rarity === 'Rare' ? 65 : 30), emoji:o.icon, description:o.description, effect:Object.entries(o.effects).map(([k,v]) => `${k} ${v}`).join(', '), source:'care' as const, careOption:{ ...o, itemId:id }, statEffects:o.effects }; });
    const byId = new Map<string, ShopCatalogItem>(); [...base, ...care].forEach((i) => byId.set(i.id, i)); return Array.from(byId.values());
  }, []);
  const visibleShopItems = shopCatalog.filter((item) => item.category === shopTab && item.name.toLowerCase().includes(shopQuery.toLowerCase()));
  const buyCatalogItem = (item: ShopCatalogItem, qty = 1, useNow = false) => {
    if (!requireTrialAccess()) return;
    const total = item.price * qty;
    if (save.userCoins < total) { notify('Not enough coins!', 'warning'); return; }
    if (useNow && activePet) {
      if (item.careOption) {
        const tempInventory = addInventory(save.inventory, item.id, qty);
        const resolved = applyCareOption(activePet, { ...item.careOption, itemId:item.id, coinCost:0, consumesItem:true, isFreeDaily:false }, tempInventory, save.userCoins - total);
        if (!resolved.result.ok) { notify(resolved.result.reason ?? 'Cannot use now', 'warning'); return; }
        updateSave((s) => ({ ...s, userCoins: resolved.coins, inventory: resolved.inventory, pets: s.pets.map((p) => p.id === activePet.id ? resolved.pet : p) }));
        notify(`Bought & used ${item.name}!`, 'success'); pushLog(`Bought & used ${item.name}.`); setDialog(resolved.result.dialog); triggerAnimation(resolved.result.petAnimation); return;
      }
      if (item.statEffects) {
        updateSave((s) => ({ ...s, userCoins: Math.max(0, s.userCoins - total), pets: s.pets.map((p) => p.id === activePet.id ? levelPet(applyStats(p, item.statEffects ?? {})).pet : p) }));
        notify(`Bought & used ${item.name}!`, 'success'); pushLog(`Bought & used ${item.name}.`); triggerAnimation(item.category === 'Food' ? 'eat' : 'play'); return;
      }
    }
    updateSave((s) => ({ ...s, userCoins: Math.max(0, s.userCoins - total), inventory: addInventory(s.inventory, item.id, qty) }));
    notify(`Bought ${qty}x ${item.name}`, 'success'); pushLog(`Bought ${qty}x ${item.name}.`); triggerAnimation('buyItem');
  };
  const useInventoryItem = (inv: InventoryItem) => { if (!requireTrialAccess()) return; const catalog = shopCatalog.find((i) => i.id === inv.itemId); const item = itemById(inv.itemId); if (!activePet || inv.quantity <= 0) return; if (catalog?.careOption) { performCare({ ...catalog.careOption, itemId: inv.itemId, coinCost:0, consumesItem: true, isFreeDaily: false }); return; } if (item?.category === 'Food' || item?.category === 'Toys') { updateActivePet((p) => levelPet(applyStats(p, item.statEffects ?? { hunger: 8, happiness: 4, xp: 2 })).pet); if (item.category === 'Food') updateSave((s) => ({ ...s, inventory: s.inventory.map((i) => i.itemId === inv.itemId ? { ...i, quantity: Math.max(0, i.quantity - 1) } : i).filter((i) => i.quantity > 0) })); notify(`Used ${item.name}`, 'success'); pushLog(`Used ${item.name}.`); triggerAnimation(item.category === 'Food' ? 'eat' : 'play'); return; } if (item) { updateActivePet((p) => ({ ...p, equippedAccessory: item.category === 'Accessories' ? item.id : p.equippedAccessory, equippedHabitat: item.category === 'Habitats' ? item.id : p.equippedHabitat, equippedDecorations: item.category === 'Decorations' ? Array.from(new Set([...p.equippedDecorations, item.id])).slice(-3) : p.equippedDecorations })); updateSave((s) => ({ ...s, inventory: s.inventory.map((i) => i.itemId === inv.itemId ? { ...i, equipped:true } : i) })); notify(`Equipped ${item.name}`, 'success'); triggerAnimation('equipItem'); } };
  const claimDaily = () => { if (!requireTrialAccess()) return; if (!dailyReady) return; const last = save.dailyReward.lastClaimDate; const diff = last ? Math.round((new Date(todayKey()).getTime() - new Date(last).getTime()) / 86400000) : 1; const streak = diff === 1 ? save.dailyReward.streak + 1 : 1; const coins = 50 + Math.min(6, streak - 1) * 15; updateSave((s) => ({ ...s, userCoins:s.userCoins + coins, dailyReward:{ lastClaimDate:todayKey(), streak } })); notify(`Daily reward claimed! +${coins}`, 'success'); pushLog(`Claimed daily reward +${coins}.`); setDailyOpen(false); };
  const exportSave = () => { const blob = new Blob([JSON.stringify(save, null, 2)], { type:'application/json' }); const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = 'pixel-paws-save.json'; a.click(); URL.revokeObjectURL(a.href); };
  const importSave = (v: string) => { if (!requireTrialAccess()) return; const parsed = safeParseSave(v); setSave(parsed); notify('Import save berhasil.', 'success'); };

  const firebaseConfigured = isFirebaseConfigured();
  if (firebaseConfigured && !auth.authReady) return <main className="grid min-h-screen place-items-center bg-[var(--bg)] font-pixel text-xs">Loading login...</main>;
  if (firebaseConfigured && !auth.isAuthenticated) return <LoginPage />;
  if (!loaded) return <main className="grid min-h-screen place-items-center bg-[var(--bg)] font-pixel text-xs">Loading save...</main>;
  return <main className={`${themeClass} ${save.settings.reducedMotion ? 'reduced-motion' : ''} min-h-screen overflow-x-hidden bg-[var(--bg)] font-pixel`}><ToastProvider toasts={toasts} />{auth.isGuest && !auth.isGuestTrialExpired && <div className="mx-auto w-full max-w-7xl px-2 pt-2 sm:px-3"><GuestTrialBadge remainingMs={auth.guestTrialRemainingMs} onLogin={() => void auth.signOutUser()} /></div>}{auth.isGuestTrialExpired && <TrialExpiredGate onEmailLogin={() => void auth.signOutUser()} />}{tutorialOpen && <TutorialModal close={() => { window.localStorage.setItem(TUTORIAL_KEY, 'yes'); setTutorialOpen(false); }} />}{dailyOpen && <DailyRewardModal save={save} claim={claimDaily} close={() => setDailyOpen(false)} />}{confirm && <ConfirmModal title="Konfirmasi Reset" body="Data yang dipilih akan dihapus dari LocalStorage." onCancel={() => setConfirm(null)} onConfirm={() => { if (confirm === 'all') { setSave(defaultSave()); window.localStorage.removeItem(SAVE_KEY); } else if (activePet) updateSave((s) => ({ ...s, pets:s.pets.filter((p) => p.id !== activePet.id), activePetId:s.pets.find((p) => p.id !== activePet.id)?.id ?? null })); setConfirm(null); }} />}{!auth.isGuestTrialExpired && activeAction && activePet && <CarePickerModal action={activeAction} pet={activePet} inventory={save.inventory} coins={save.userCoins} onClose={() => setActiveAction(null)} onPick={performCare} />}{!auth.isGuestTrialExpired && shopDetail && <ShopDetailModal item={shopDetail} coins={save.userCoins} owned={save.inventory.find((i) => i.itemId === shopDetail.id)?.quantity ?? 0} hasPet={!!activePet} onClose={() => setShopDetail(null)} onBuy={buyCatalogItem} />}
    <div className="mx-auto flex w-full max-w-7xl gap-3 p-2 pb-24 sm:p-3 md:pb-3"><Sidebar page={page} setPage={setPage} coins={save.userCoins} openDaily={() => { if (requireTrialAccess()) setDailyOpen(true); }} />
      <div className="min-w-0 flex-1 overflow-hidden">{page === 'Couple' ? (auth.isGuestTrialExpired ? <LockedCard message="Guest trial ended. Login to play together." onClick={() => requireTrialAccess('Guest trial ended. Login to play together.')} /> : <CoupleModePage />) : !activePet ? <AnimalSelect selected={selectedAnimal} setSelected={setSelectedAnimal} name={petName} setName={setPetName} adopt={() => adopt()} /> : game !== 'none' ? <MiniGame game={game} setGame={setGame} reward={(coins, xp, happy) => { if (!requireTrialAccess()) return; updateSave((s) => ({ ...s, userCoins:s.userCoins + coins })); updateActivePet((p) => levelPet(applyStats(p, { xp, happiness:happy })).pet); notify(`Reward 🪙${coins}`, 'success'); }} /> : page === 'Pet' ? <Dashboard pet={activePet} mood={mood} dialog={dialog} save={save} logs={logs} setPage={setPage} activeAnimation={activeAnimation} doAction={(action) => { if (requireTrialAccess()) setActiveAction(action); }} setName={(n) => updateActivePet((p) => ({ ...p, customName:n }))} timeOfDay={timeOfDay} /> : page === 'Shop' ? <Shop items={visibleShopItems} allTabs={['Food','Snacks','Toys','Medicine','Accessories','Decorations','Habitats','Special']} tab={shopTab} setTab={setShopTab} query={shopQuery} setQuery={setShopQuery} save={save} pet={activePet} dailyReady={dailyReady} openDaily={() => { if (requireTrialAccess()) setDailyOpen(true); }} buy={buyCatalogItem} openDetail={setShopDetail} /> : page === 'Inventory' ? <Inventory save={save} catalog={shopCatalog} useItem={useInventoryItem} unequip={(id) => { if (!requireTrialAccess()) return; updateSave((s) => ({ ...s, inventory:s.inventory.map((i) => i.itemId === id ? { ...i, equipped:false } : i) })); }} /> : page === 'Games' ? <Games setGame={(next) => { if (requireTrialAccess()) setGame(next); }} /> : page === 'Achievements' ? <Achievements save={save} /> : page === 'Dex' ? <Dex save={save} adopt={adopt} setActive={(id) => { if (!requireTrialAccess()) return; updateSave((s) => ({ ...s, activePetId:id })); }} unlock={(a) => { if (!requireTrialAccess()) return; updateSave((s) => s.userCoins >= a.unlockCost ? { ...s, userCoins:s.userCoins-a.unlockCost, unlockedAnimals:[...s.unlockedAnimals,a.id] } : (notify('Not enough coins!', 'warning'), s)); }} /> : <SettingsPanel save={save} setTheme={(theme) => updateSave((s) => ({ ...s, settings:{ ...s.settings, theme } }))} toggleSound={() => updateSave((s) => ({ ...s, settings:{ ...s.settings, sound:!s.settings.sound } }))} toggleMotion={() => updateSave((s) => ({ ...s, settings:{ ...s.settings, reducedMotion:!s.settings.reducedMotion } }))} exportSave={exportSave} importSave={importSave} resetPet={() => setConfirm('pet')} resetAll={() => setConfirm('all')} />}</div>
    </div><BottomNav page={page} setPage={setPage} /></main>;
}

function LockedCard({ message, onClick }: { message: string; onClick: () => void }) { return <PixelCard className="bg-yellow-100"><h2 className="mb-2 text-sm">Locked</h2><p className="mb-3 text-[10px] leading-relaxed">{message}</p><PixelButton onClick={onClick}>Login to continue</PixelButton></PixelCard>; }
function Sidebar({ page, setPage, coins, openDaily }: { page: string; setPage: (p: string) => void; coins: number; openDaily: () => void }) { return <aside className="hidden w-56 shrink-0 md:block"><PixelCard className="sticky top-3"><h1 className="mb-2 text-sm leading-relaxed">Pixel Paws</h1><p className="mb-4 text-[10px]">🪙 {coins}</p><div className="grid gap-2">{navItems.map((n) => <PixelButton key={n} onClick={() => setPage(n)} tone={page === n ? 'bg-yellow-200' : 'bg-white'}>{n}</PixelButton>)}<PixelButton onClick={openDaily}>Daily</PixelButton></div></PixelCard></aside>; }
function BottomNav({ page, setPage }: { page: string; setPage: (p: string) => void }) { const nav = [['Pet','🐾'],['Shop','🛒'],['Games','🎮'],['Couple','💞'],['Dex','📚'],['Settings','⚙️']]; return <nav className="fixed bottom-0 left-0 right-0 z-30 grid grid-cols-6 gap-1 border-t-4 border-slate-950 bg-white p-1 pb-[max(0.5rem,env(safe-area-inset-bottom))] md:hidden">{nav.map(([n,e]) => <button key={n} type="button" onClick={() => setPage(n)} className={`min-w-0 border-2 border-slate-950 p-1 text-[8px] leading-tight ${page===n?'bg-yellow-200':'bg-[var(--soft)]'}`}>{e}<br />{n}</button>)}</nav>; }
function TutorialModal({ close }: { close: () => void }) { return <div className="fixed inset-0 z-50 grid place-items-end bg-black/50 p-0 md:place-items-center md:p-4"><PixelCard className="max-h-[90vh] w-full overflow-auto rounded-t-xl md:w-[calc(100vw-24px)] md:max-w-2xl md:rounded-none"><h2 className="mb-3 text-sm">How to Play Pixel Paws</h2><div className="space-y-3 text-[10px] leading-relaxed"><p>1. Pilih hewan pertama, beri nama, lalu rawat seperti Tamagotchi.</p><p>2. Klik action seperti Feed/Play/Clean untuk membuka pilihan detail. Pilih item yang cocok agar stat naik lebih besar.</p><p>3. Beli item di Shop. Coin selalu terlihat di sticky wallet saat scroll.</p><p>4. Pakai Inventory untuk food, snack, medicine, toys, accessory, decoration, dan habitat.</p><p>5. Buka Couple untuk main online dengan invite code Firebase.</p></div><PixelButton onClick={close} tone="mt-4 bg-yellow-200">Aku Mengerti</PixelButton></PixelCard></div>; }
function DailyRewardModal({ save, claim, close }: { save: SaveData; claim: () => void; close: () => void }) { const can = save.dailyReward.lastClaimDate !== todayKey(); return <div className="fixed inset-0 z-40 grid place-items-end bg-black/50 p-0 sm:place-items-center sm:p-4"><PixelCard className="max-h-[85vh] w-full overflow-y-auto rounded-t-2xl sm:w-[calc(100vw-24px)] sm:max-w-lg sm:rounded-none"><h2 className="mb-3 text-sm">Daily Reward</h2><div className="grid grid-cols-4 gap-2 sm:grid-cols-7">{Array.from({ length: 7 }, (_, i) => <div key={i} className={`border-2 border-slate-950 p-2 text-center text-[9px] ${i < save.dailyReward.streak % 7 ? 'bg-yellow-200' : 'bg-white'}`}>D{i+1}<br />🪙{50+i*15}</div>)}</div><p className="my-3 text-[10px]">Streak: {save.dailyReward.streak} hari</p><div className="flex flex-col gap-2 sm:flex-row"><PixelButton disabled={!can} onClick={claim}>Claim</PixelButton><PixelButton onClick={close} tone="bg-white">Tutup</PixelButton></div></PixelCard></div>; }
function AnimalSelect({ selected, setSelected, name, setName, adopt }: { selected: string; setSelected: (s: string) => void; name: string; setName: (s: string) => void; adopt: () => void }) { return <div className="grid gap-4"><PixelCard><h1 className="text-lg leading-relaxed">Pixel Paws: 8-Bit Animal Tamagotchi</h1><p className="mt-3 text-[10px] leading-relaxed">Pilih hewan pertama dan beri nama custom. Progress tersimpan di LocalStorage.</p><input value={name} onChange={(e) => setName(e.target.value)} placeholder="Nama pet" className="mt-4 w-full border-4 border-slate-950 p-3 text-xs" /><PixelButton onClick={adopt} tone="mt-3 bg-yellow-200">Mulai Adopt</PixelButton></PixelCard><div className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-3">{animals.slice(0,12).map((a) => <AnimalCard key={a.id} animal={a} unlocked={true} owned={false} onSelect={() => setSelected(a.id)} onUnlock={() => setSelected(a.id)} />)}</div><p className="text-[10px]">Terpilih: {getAnimal(selected).species}</p></div>; }
function AnimalCard({ animal, unlocked, owned, onSelect, onUnlock }: { animal: Animal; unlocked: boolean; owned: boolean; onSelect: () => void; onUnlock: () => void }) { return <PixelCard className="text-center"><div className={`text-5xl ${unlocked ? '' : 'grayscale brightness-0'}`}>{animal.emoji}</div><h3 className="mt-2 text-xs">{animal.species}</h3><p className="my-2 text-[9px] leading-relaxed">{animal.personality}</p>{owned ? <PixelButton onClick={onSelect}>Aktifkan</PixelButton> : unlocked ? <PixelButton onClick={onSelect}>Adopsi</PixelButton> : <PixelButton onClick={onUnlock}>Unlock 🪙{animal.unlockCost}</PixelButton>}</PixelCard>; }
function Dashboard({ pet, mood, dialog, save, logs, doAction, setName, activeAnimation, timeOfDay, setPage }: { pet: Pet; mood: Mood; dialog: string; save: SaveData; logs: string[]; doAction: (k: CareAction) => void; setName: (n: string) => void; activeAnimation: PetAnimationType; timeOfDay: string; setPage: (p: string) => void }) { const animal = getAnimal(pet.animalId); const age = Math.max(1, Math.floor((Date.now() - pet.birthDate)/86400000)+1); return <div className="grid w-full max-w-full grid-cols-1 gap-3 xl:grid-cols-[minmax(0,1.15fr)_minmax(0,.85fr)] xl:gap-4"><PixelCard className="text-center"><div className="mb-3 flex flex-wrap items-center justify-between gap-2 text-[10px]"><span>🕹️ Hari {age}</span><span>{timeOfDay}</span><span>{save.weather}</span><span>🪙 {save.userCoins}</span></div><div className="relative max-w-full overflow-hidden rounded bg-[var(--soft)] p-3 sm:p-5"><PixelSceneDecor habitat={pet.equippedHabitat ? itemById(pet.equippedHabitat)?.name ?? animal.favoriteHabitat : animal.favoriteHabitat} weather={save.weather} time={timeOfDay} animation={activeAnimation} /><PetSprite pet={pet} mood={mood} animation={activeAnimation} reduced={save.settings.reducedMotion} /></div><PetDialog text={`${animal.species}: ${dialog}`} /><div className="mt-4 grid grid-cols-1 gap-2 text-left sm:grid-cols-2"><input value={pet.customName} onChange={(e) => setName(e.target.value)} className="border-4 border-slate-950 p-2 text-[10px]" /><p className="text-[10px] leading-relaxed">Species: {animal.species}<br />Level {pet.level}/50 · {getEvolution(pet.level)}<br />Mood: {mood}<br />Fav: {animal.favoriteFood}, {animal.favoriteToy}, {animal.favoriteHabitat}</p></div></PixelCard><div className="grid gap-4"><PixelCard><h2 className="mb-3 text-sm">Stats</h2><div className="grid gap-3"><StatBar label="Kenyang" value={pet.stats.hunger} color="bg-orange-400" /><StatBar label="Bahagia" value={pet.stats.happiness} color="bg-pink-400" /><StatBar label="Energi" value={pet.stats.energy} color="bg-blue-400" /><StatBar label="Kebersihan" value={pet.stats.cleanliness} color="bg-cyan-300" /><StatBar label="Kesehatan" value={pet.stats.health} color="bg-green-400" /><StatBar label="Kasih sayang" value={pet.stats.affection} color="bg-red-300" /><StatBar label={`XP / ${xpNeed(pet.level)}`} value={(pet.stats.xp / xpNeed(pet.level))*100} color="bg-purple-400" /></div></PixelCard><ActionGrid pet={pet} mood={mood} doAction={doAction} /><PixelCard><h2 className="mb-2 text-sm">Daily Mini Goal</h2><p className="text-[10px] leading-relaxed">Keep happiness above 80 or go for a walk. Reward muncul lewat action dan activity log.</p><PixelButton onClick={() => setPage('Shop')} tone="mt-3 bg-white">Open Shop</PixelButton></PixelCard><ActivityLog logs={logs} /></div></div>; }
function ActionGrid({ pet, mood, doAction }: { pet: Pet; mood: Mood; doAction: (k: CareAction) => void }) { return <PixelCard><h2 className="mb-3 text-sm">Care Actions</h2><div className="grid grid-cols-2 gap-2 sm:grid-cols-3">{actionCards.map((a) => { const reason = a.key === 'wake' && !pet.isSleeping ? 'Awake' : a.key === 'sleep' && pet.isSleeping ? 'Sleeping' : (mood === 'Very Sick' && ['play','walk','train'].includes(a.key)) ? 'Very sick' : null; return <button key={a.key} type="button" onClick={() => reason ? undefined : doAction(a.key)} disabled={!!reason} title={reason ?? a.description} className="pixel-border-sm bg-white p-3 text-left text-[10px] disabled:opacity-50"><span className="text-lg">{a.icon}</span><br />{a.label}<br /><span className="text-[8px]">{reason ?? a.description}</span></button>; })}</div></PixelCard>; }
function ActivityLog({ logs }: { logs: string[] }) { return <PixelCard><h2 className="mb-2 text-sm">Recent Activity</h2><div className="max-h-44 space-y-2 overflow-auto text-[9px]">{logs.length ? logs.map((l, i) => <div key={`${l}-${i}`} className="border-2 border-slate-950 bg-white p-2">{l}</div>) : <p>Belum ada aktivitas. Coba Feed atau Play!</p>}</div></PixelCard>; }
function CarePickerModal({ action, pet, inventory, coins, onClose, onPick }: { action: CareAction; pet: Pet; inventory: InventoryItem[]; coins: number; onClose: () => void; onPick: (option: CareOption) => void }) { const options = careOptionsByAction[action] ?? []; const title = actionCards.find((a) => a.key === action)?.label ?? action; return <div className="fixed inset-0 z-40 grid items-end bg-black/50 p-0 md:place-items-center md:p-4"><PixelCard className="max-h-[88vh] w-full overflow-auto rounded-t-xl md:w-[calc(100vw-24px)] md:max-w-3xl"><div className="sticky top-0 z-10 -mx-3 -mt-3 mb-3 flex flex-col gap-2 border-b-4 border-slate-950 bg-[var(--panel)] p-3 sm:-mx-4 sm:-mt-4 sm:flex-row sm:items-center sm:justify-between "><div><h2 className="text-sm">{title} Picker</h2><p className="mt-1 text-[9px]">Pilih opsi, lihat efek, dan hindari tombol disabled.</p></div><PixelButton onClick={onClose} tone="bg-white">Cancel</PixelButton></div><div className="grid grid-cols-1 gap-3 sm:grid-cols-2">{options.map((option) => { const reason = optionDisabledReason(pet, option, inventory, coins); const itemId = option.itemId ?? (option.itemName ? shopItems.find((i) => i.name === option.itemName)?.id ?? option.id : undefined); const qty = itemId ? inventory.find((i) => i.itemId === itemId)?.quantity ?? 0 : 0; const animal = getAnimal(pet.animalId); const favorite = option.favoriteSpecies?.includes(animal.species) || option.name === animal.favoriteFood || option.name === animal.favoriteToy || option.name === animal.favoriteHabitat; return <div key={option.id} className="border-4 border-slate-950 bg-white p-3"><div className="flex items-start gap-3"><div className="text-3xl">{option.icon}</div><div className="min-w-0 flex-1 overflow-hidden"><h3 className="text-xs">{option.name}</h3><p className="my-2 text-[9px] leading-relaxed">{option.description}</p><p className="text-[9px]">{Object.entries(option.effects).map(([k,v]) => `${k} ${Number(v) > 0 ? '+' : ''}${v}`).join(' · ')}</p><p className="mt-1 text-[9px]">Lv {option.unlockLevel} · {option.rarity}{option.coinCost ? ` · 🪙${option.coinCost}` : ''}{option.consumesItem ? ` · Owned ${qty}` : ''}</p>{favorite && <span className="mt-2 inline-block border-2 border-slate-950 bg-yellow-200 px-2 py-1 text-[8px]">Favorite Bonus</span>}{reason && <p className="mt-2 text-[9px] text-red-700">{reason}</p>}</div></div><PixelButton disabled={!!reason} onClick={() => onPick(option)} tone="mt-3 w-full bg-[var(--accent)]">Select</PixelButton></div>; })}</div></PixelCard></div>; }
function ShopStickyWallet({ coins, pet, dailyReady, openDaily }: { coins: number; pet: Pet | null; dailyReady: boolean; openDaily: () => void }) { return <div className="sticky top-0 z-20 mb-3 border-4 border-slate-950 bg-white/95 p-3 shadow-pixelSm backdrop-blur md:top-4"><div className="flex flex-wrap items-center justify-between gap-2 text-[10px]"><span>🪙 {coins.toLocaleString()} Coins</span><span>{pet ? `${pet.customName} Lv. ${pet.level}` : 'No active pet'}</span><PixelButton onClick={openDaily} disabled={!dailyReady} tone={dailyReady ? 'bg-yellow-200' : 'bg-slate-200'}>{dailyReady ? 'Daily Ready' : 'Daily Claimed'}</PixelButton></div></div>; }
function Shop({ items, allTabs, tab, setTab, query, setQuery, save, pet, dailyReady, openDaily, buy, openDetail }: { items: ShopCatalogItem[]; allTabs: ShopTab[]; tab: ShopTab; setTab: (t: ShopTab) => void; query: string; setQuery: (q: string) => void; save: SaveData; pet: Pet | null; dailyReady: boolean; openDaily: () => void; buy: (i: ShopCatalogItem, qty?: number) => void; openDetail: (i: ShopCatalogItem) => void }) { return <div className="grid gap-3"><ShopStickyWallet coins={save.userCoins} pet={pet} dailyReady={dailyReady} openDaily={openDaily} /><div className="sticky top-[86px] z-10 grid gap-2 border-4 border-slate-950 bg-[var(--panel)] p-3 md:top-24"><input value={query} onChange={(e) => setQuery(e.target.value)} className="w-full border-4 border-slate-950 p-2 text-[10px]" placeholder="Search item..." /><div className="no-scrollbar flex gap-2 overflow-x-auto pb-1">{allTabs.map((c) => <PixelButton key={c} onClick={() => setTab(c)} tone={tab===c?'bg-yellow-200':'bg-white'}>{c}</PixelButton>)}</div></div><div className="grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-3">{items.length ? items.map((item) => <PixelCard key={item.id}><button type="button" onClick={() => openDetail(item)} className="w-full text-left"><div className="text-3xl">{item.emoji}</div><h3 className="mt-2 text-xs">{item.name}</h3><p className="my-2 text-[9px] leading-relaxed">{item.description}</p><p className="text-[9px]">{item.effect}</p></button><div className="mt-3 flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><span className="text-[10px]">🪙{item.price}</span><PixelButton disabled={save.userCoins < item.price} onClick={() => buy(item)}>{save.userCoins < item.price ? 'Need Coins' : 'Buy'}</PixelButton></div></PixelCard>) : <PixelCard className="md:col-span-2 xl:col-span-3">No item found.</PixelCard>}</div></div>; }
function ShopDetailModal({ item, coins, owned, hasPet, onClose, onBuy }: { item: ShopCatalogItem; coins: number; owned: number; hasPet: boolean; onClose: () => void; onBuy: (i: ShopCatalogItem, qty?: number, useNow?: boolean) => void }) { const consumable = ['Food','Snacks','Medicine','Toys'].includes(item.category); return <div className="fixed inset-0 z-40 grid place-items-end bg-black/50 p-0 md:place-items-center md:p-4"><PixelCard className="max-h-[85vh] w-full overflow-y-auto rounded-t-2xl md:w-[calc(100vw-24px)] md:max-w-xl md:rounded-none"><div className="text-center text-6xl">{item.emoji}</div><h2 className="mt-3 text-sm">{item.name}</h2><p className="my-3 text-[10px] leading-relaxed">{item.description}</p><p className="text-[10px]">Category: {item.category} · Price: 🪙{item.price} · Owned: {owned}</p><p className="mt-2 text-[10px]">Effect: {item.effect}</p><div className="mt-4 flex flex-col gap-2 sm:flex-row sm:flex-wrap"><PixelButton disabled={coins < item.price} onClick={() => onBuy(item, 1)}>Buy 1</PixelButton>{consumable && <PixelButton disabled={coins < item.price * 5} onClick={() => onBuy(item, 5)} tone="bg-yellow-200">Buy 5</PixelButton>}{consumable && hasPet && <PixelButton disabled={coins < item.price} onClick={() => { onBuy(item, 1, true); onClose(); }} tone="bg-green-200">Buy & Use</PixelButton>}<PixelButton onClick={onClose} tone="bg-white">Close</PixelButton></div></PixelCard></div>; }
function Inventory({ save, catalog, useItem, unequip }: { save: SaveData; catalog: ShopCatalogItem[]; useItem: (i: InventoryItem) => void; unequip: (id: string) => void }) { return <div className="grid gap-4"><PixelCard><h2 className="text-sm">Inventory</h2><p className="mt-2 text-[10px]">Semua item bisa digunakan, dipakai, atau di-equip sesuai kategori.</p></PixelCard>{save.inventory.length ? <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-3">{save.inventory.map((inv) => { const item = itemById(inv.itemId); const c = catalog.find((x) => x.id === inv.itemId); return <PixelCard key={inv.itemId}><div className="text-3xl">{item?.emoji ?? c?.emoji ?? '🎁'}</div><h3 className="mt-2 text-xs">{item?.name ?? c?.name ?? inv.itemId} x{inv.quantity}</h3><p className="my-2 text-[9px]">{item?.category ?? c?.category ?? 'Item'} · {inv.equipped ? 'Equipped' : item?.effect ?? c?.effect ?? 'Usable'}</p><div className="flex flex-col gap-2 sm:flex-row sm:flex-wrap"><PixelButton disabled={inv.quantity <= 0} onClick={() => useItem(inv)}>{item?.category === 'Accessories' || item?.category === 'Decorations' || item?.category === 'Habitats' ? 'Equip' : 'Use'}</PixelButton>{inv.equipped && <PixelButton onClick={() => unequip(inv.itemId)} tone="bg-white">Unequip</PixelButton>}</div></PixelCard>; })}</div> : <PixelCard>Inventory kosong. Beli item di Shop dulu.</PixelCard>}</div>; }
function Achievements({ save }: { save: SaveData }) { return <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-3">{achievements.map((a) => <PixelCard key={a.id} className={save.achievements.includes(a.id) ? 'bg-yellow-100' : ''}><div className="text-3xl">{a.badge}</div><h3 className="mt-2 text-xs">{a.title}</h3><p className="my-2 text-[9px] leading-relaxed">{a.description}</p><p className="text-[9px]">Reward 🪙{a.reward} · {save.achievements.includes(a.id) ? 'Claimed' : 'Locked'}</p></PixelCard>)}</div>; }
function Dex({ save, adopt, setActive, unlock }: { save: SaveData; adopt: (id: string, name?: string) => void; setActive: (id: string) => void; unlock: (a: Animal) => void }) { return <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-3">{animals.map((a) => { const ownedPet = save.pets.find((p) => p.animalId === a.id); return <AnimalCard key={a.id} animal={a} unlocked={save.unlockedAnimals.includes(a.id)} owned={!!ownedPet} onSelect={() => ownedPet ? setActive(ownedPet.id) : adopt(a.id, a.species)} onUnlock={() => unlock(a)} />; })}</div>; }
function SettingsPanel({ save, setTheme, toggleSound, toggleMotion, exportSave, importSave, resetPet, resetAll }: { save: SaveData; setTheme: (t: ThemeName) => void; toggleSound: () => void; toggleMotion: () => void; exportSave: () => void; importSave: (v: string) => void; resetPet: () => void; resetAll: () => void }) { const themes: ThemeName[] = ['Green Retro','Pink Candy','Blue Ocean','Yellow Pixel','Dark Arcade']; return <PixelCard><h2 className="mb-3 text-sm">Settings</h2><div className="flex flex-col gap-2 sm:flex-row sm:flex-wrap">{themes.map((t) => <PixelButton key={t} onClick={() => setTheme(t)} tone={save.settings.theme === t ? 'bg-yellow-200' : 'bg-white'}>{t}</PixelButton>)}</div><div className="mt-4 flex flex-col gap-2 sm:flex-row sm:flex-wrap"><PixelButton onClick={toggleSound}>Sound {save.settings.sound ? 'On' : 'Off'}</PixelButton><PixelButton onClick={toggleMotion}>Motion {save.settings.reducedMotion ? 'Reduced' : 'On'}</PixelButton><PixelButton onClick={exportSave}>Export JSON</PixelButton><label className="pixel-border-sm cursor-pointer bg-white px-3 py-2 text-[10px]">Import JSON<input className="hidden" type="file" accept="application/json" onChange={(e) => { const file = e.target.files?.[0]; if (file) void file.text().then(importSave); }} /></label><PixelButton onClick={resetPet} tone="bg-orange-200">Reset Pet</PixelButton><PixelButton onClick={resetAll} tone="bg-red-300">Reset All</PixelButton></div></PixelCard>; }
function Games({ setGame }: { setGame: (g: 'catch'|'memory'|'rhythm') => void }) { return <div className="grid grid-cols-1 gap-3 md:grid-cols-3"><PixelCard><h3 className="text-sm">Catch the Food</h3><p className="my-3 text-[10px]">Klik makanan random untuk coin.</p><PixelButton onClick={() => setGame('catch')}>Play</PixelButton></PixelCard><PixelCard><h3 className="text-sm">Memory Match</h3><p className="my-3 text-[10px]">Cocokkan kartu pixel.</p><PixelButton onClick={() => setGame('memory')}>Play</PixelButton></PixelCard><PixelCard><h3 className="text-sm">Tap Rhythm</h3><p className="my-3 text-[10px]">Tap urutan tombol.</p><PixelButton onClick={() => setGame('rhythm')}>Play</PixelButton></PixelCard></div>; }
function MiniGame({ game, setGame, reward }: { game: 'catch'|'memory'|'rhythm'; setGame: (g: 'none') => void; reward: (c: number, xp?: number, h?: number) => void }) { const [time, setTime] = useState(25); const [score, setScore] = useState(0); const [pos, setPos] = useState({ left: 40, top: 40 }); const [flipped, setFlipped] = useState<number[]>([]); const rewarded = useRef(false); const cards = ['🐱','🐶','🐰','🐹','🐱','🐶','🐰','🐹']; useEffect(() => { const id = window.setInterval(() => setTime((t) => Math.max(0, t-1)), 1000); return () => window.clearInterval(id); }, []); useEffect(() => { if (time === 0 && !rewarded.current) { rewarded.current = true; reward(score * 5, game === 'rhythm' ? score * 3 : 0, score); setGame('none'); } }, [time, score, reward, game, setGame]); if (game === 'memory') return <PixelCard><h2 className="mb-3 text-sm">Memory Match · {time}s · Score {score}</h2><div className="grid max-w-full grid-cols-4 gap-2 sm:max-w-md">{cards.map((c,i) => <button type="button" key={`${c}-${i}`} onClick={() => { if (!flipped.includes(i)) { const next = [...flipped, i]; setFlipped(next); if (next.filter((x) => cards[x] === c).length === 2) setScore((s) => s+2); } }} className="h-14 border-4 border-slate-950 bg-white text-2xl sm:h-20 sm:text-3xl">{flipped.includes(i) ? c : '?'}</button>)}</div><PixelButton onClick={() => setGame('none')} tone="mt-4 bg-white">Back</PixelButton></PixelCard>; if (game === 'rhythm') return <PixelCard><h2 className="mb-3 text-sm">Tap Rhythm · {time}s · Score {score}</h2><div className="grid grid-cols-3 gap-3">{['◀','●','▶'].map((b,i) => <button type="button" key={b} onClick={() => setScore((s) => Math.max(0, s + (i === s % 3 ? 2 : -1)))} className={`h-16 border-4 border-slate-950 text-2xl sm:h-24 sm:text-3xl ${i === score % 3 ? 'bg-yellow-200' : 'bg-white'}`}>{b}</button>)}</div><PixelButton onClick={() => setGame('none')} tone="mt-4 bg-white">Back</PixelButton></PixelCard>; return <PixelCard><h2 className="mb-3 text-sm">Catch the Food · {time}s · Score {score}</h2><div className="relative h-64 max-w-full overflow-hidden border-4 sm:h-80 border-slate-950 bg-sky-100"><button type="button" className="absolute text-4xl" style={{ left:`${pos.left}%`, top:`${pos.top}%` }} onClick={() => { setScore((s) => s+1); setPos({ left: Math.random()*82, top: Math.random()*72 }); }}>🍎</button></div><PixelButton onClick={() => setGame('none')} tone="mt-4 bg-white">Back</PixelButton></PixelCard>; }
