'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { achievements, animals, dialogs, shopItems } from '@/lib/gameData';
import { addInventory, applyStats, clamp, defaultSave, getAnimal, getEvolution, getMood, getTimeOfDay, getUnlockedAchievements, itemById, levelPet, newPet, randomWeather, safeParseSave, todayKey, xpNeed } from '@/lib/gameLogic';
import CoupleModePage from '@/src/components/couple/CoupleModePage';
import type { Achievement, Animal, InventoryItem, ItemCategory, Mood, Pet, SaveData, ShopItem, Stats, ThemeName, Toast } from '@/lib/types';

const SAVE_KEY = 'pixel-pals-save-v1';
const categories: ItemCategory[] = ['Food', 'Toys', 'Accessories', 'Decorations', 'Habitats'];
const actions = [
  ['feed','Feed','🍽️'], ['play','Play','🎾'], ['clean','Clean','🧼'], ['sleep','Sleep','💤'], ['wake','Wake Up','☀️'], ['medicine','Medicine','💊'], ['pet','Pet','💖'], ['walk','Walk','🚶'], ['train','Train','🏋️'], ['snack','Snack','🍪'],
] as const;

function PixelButton({ children, onClick, disabled, tone = 'bg-[var(--accent)]', type = 'button' }: { children: React.ReactNode; onClick?: () => void; disabled?: boolean; tone?: string; type?: 'button' | 'submit' }) {
  return <button type={type} onClick={onClick} disabled={disabled} className={`pixel-border-sm ${tone} px-3 py-2 text-[10px] leading-relaxed text-slate-950 transition active:translate-x-1 active:translate-y-1 active:shadow-none disabled:cursor-not-allowed disabled:opacity-50`}>{children}</button>;
}
function PixelCard({ children, className = '' }: { children: React.ReactNode; className?: string }) { return <section className={`pixel-border bg-[var(--panel)] p-4 ${className}`}>{children}</section>; }
function StatBar({ label, value, color }: { label: string; value: number; color: string }) { const safe = clamp(value); return <div><div className="mb-1 flex justify-between text-[9px]"><span>{label}</span><span>{Math.round(safe)}/100</span></div><div className="h-4 border-2 border-slate-950 bg-white"><div className={`h-full ${color}`} style={{ width: `${safe}%` }} /></div></div>; }
function PetSprite({ pet, mood, reduced }: { pet: Pet; mood: Mood; reduced: boolean }) { const animal = getAnimal(pet.animalId); const evo = getEvolution(pet.level); const size = evo === 'Adult' ? 'text-8xl' : evo === 'Teen' ? 'text-7xl' : evo === 'Kid' ? 'text-6xl' : 'text-5xl'; const anim = reduced ? '' : mood === 'Sakit' || mood === 'Very Sick' ? 'animate-sick' : mood === 'Senang' || mood === 'Manja' ? 'animate-happy' : 'animate-idle'; return <div className={`mx-auto flex h-44 w-44 items-center justify-center border-4 border-slate-950 bg-white ${anim}`} style={{ background: `linear-gradient(135deg, ${animal.color}, white)` }}><div className={`${size} drop-shadow`}><span>{animal.emoji}</span><span className="block text-center text-xs">{animal.expressions[mood] ?? '^_^'}</span>{pet.equippedAccessory && <span className="block text-center text-2xl">{itemById(pet.equippedAccessory)?.emoji}</span>}</div></div>; }
function PetDialog({ text }: { text: string }) { return <div className="pixel-border-sm mt-3 bg-white p-3 text-[10px] leading-relaxed">💬 {text}</div>; }
function ToastProvider({ toasts }: { toasts: Toast[] }) { return <div className="fixed right-3 top-3 z-50 space-y-2">{toasts.map((t) => <div key={t.id} className="pixel-border-sm animate-pop bg-white p-3 text-[10px]">{t.message}</div>)}</div>; }
function ConfirmModal({ title, body, onCancel, onConfirm }: { title: string; body: string; onCancel: () => void; onConfirm: () => void }) { return <div className="fixed inset-0 z-40 grid place-items-center bg-black/50 p-4"><PixelCard className="max-w-md"><h2 className="mb-3 text-sm">{title}</h2><p className="mb-4 text-[10px] leading-relaxed">{body}</p><div className="flex gap-3"><PixelButton onClick={onConfirm} tone="bg-red-300">Ya</PixelButton><PixelButton onClick={onCancel} tone="bg-white">Batal</PixelButton></div></PixelCard></div>; }
function DailyRewardModal({ save, claim, close }: { save: SaveData; claim: () => void; close: () => void }) { const can = save.dailyReward.lastClaimDate !== todayKey(); return <div className="fixed inset-0 z-40 grid place-items-center bg-black/50 p-4"><PixelCard className="max-w-lg"><h2 className="mb-3 text-sm">Daily Reward</h2><div className="grid grid-cols-7 gap-2">{Array.from({ length: 7 }, (_, i) => <div key={i} className={`border-2 border-slate-950 p-2 text-center text-[9px] ${i < save.dailyReward.streak % 7 ? 'bg-yellow-200' : 'bg-white'}`}>D{i+1}<br />🪙{50+i*15}</div>)}</div><p className="my-3 text-[10px]">Streak: {save.dailyReward.streak} hari</p><div className="flex gap-3"><PixelButton disabled={!can} onClick={claim}>Claim</PixelButton><PixelButton onClick={close} tone="bg-white">Tutup</PixelButton></div></PixelCard></div>; }
function AnimalCard({ animal, unlocked, owned, onSelect, onUnlock }: { animal: Animal; unlocked: boolean; owned: boolean; onSelect: () => void; onUnlock: () => void }) { return <PixelCard className="text-center"><div className={`text-5xl ${unlocked ? '' : 'grayscale brightness-0'}`}>{animal.emoji}</div><h3 className="mt-2 text-xs">{animal.species}</h3><p className="my-2 text-[9px] leading-relaxed">{animal.personality}</p>{owned ? <PixelButton onClick={onSelect}>Aktifkan</PixelButton> : unlocked ? <PixelButton onClick={onSelect}>Adopsi</PixelButton> : <PixelButton onClick={onUnlock}>Unlock 🪙{animal.unlockCost}</PixelButton>}</PixelCard>; }
function ShopItemCard({ item, owned, coins, buy }: { item: ShopItem; owned: boolean; coins: number; buy: () => void }) { return <PixelCard><div className="flex items-start gap-3"><div className="text-3xl">{item.emoji}</div><div className="flex-1"><h3 className="text-xs">{item.name}</h3><p className="my-2 text-[9px] leading-relaxed">{item.description}</p><p className="text-[9px]">{item.effect}</p><div className="mt-3 flex items-center justify-between"><span className="text-[10px]">🪙{item.price}</span><PixelButton disabled={coins < item.price || (owned && item.category !== 'Food')} onClick={buy}>{owned && item.category !== 'Food' ? 'Owned' : 'Buy'}</PixelButton></div></div></div></PixelCard>; }
function InventoryItemCard({ inv, useItem, unequip }: { inv: InventoryItem; useItem: () => void; unequip: () => void }) { const item = itemById(inv.itemId); if (!item) return null; return <PixelCard><div className="text-3xl">{item.emoji}</div><h3 className="mt-2 text-xs">{item.name} x{inv.quantity}</h3><p className="my-2 text-[9px]">{item.category} · {inv.equipped ? 'Equipped' : item.effect}</p><div className="flex gap-2"><PixelButton onClick={useItem}>{item.category === 'Food' ? 'Use' : 'Equip'}</PixelButton>{inv.equipped && <PixelButton onClick={unequip} tone="bg-white">Unequip</PixelButton>}</div></PixelCard>; }
function AchievementCard({ achievement, unlocked }: { achievement: Achievement; unlocked: boolean }) { return <PixelCard className={unlocked ? 'bg-yellow-100' : ''}><div className="text-3xl">{achievement.badge}</div><h3 className="mt-2 text-xs">{achievement.title}</h3><p className="my-2 text-[9px] leading-relaxed">{achievement.description}</p><p className="text-[9px]">Reward 🪙{achievement.reward} · {unlocked ? 'Claimed' : 'Locked'}</p></PixelCard>; }
function MiniGameCard({ title, desc, onClick }: { title: string; desc: string; onClick: () => void }) { return <PixelCard><h3 className="text-sm">{title}</h3><p className="my-3 text-[10px] leading-relaxed">{desc}</p><PixelButton onClick={onClick}>Play</PixelButton></PixelCard>; }
function SettingsPanel({ save, setTheme, toggleSound, toggleMotion, exportSave, importSave, resetPet, resetAll }: { save: SaveData; setTheme: (t: ThemeName) => void; toggleSound: () => void; toggleMotion: () => void; exportSave: () => void; importSave: (v: string) => void; resetPet: () => void; resetAll: () => void }) { const themes: ThemeName[] = ['Green Retro','Pink Candy','Blue Ocean','Yellow Pixel','Dark Arcade']; return <div className="grid gap-4"><PixelCard><h2 className="mb-3 text-sm">Settings</h2><div className="flex flex-wrap gap-2">{themes.map((t) => <PixelButton key={t} onClick={() => setTheme(t)} tone={save.settings.theme === t ? 'bg-yellow-200' : 'bg-white'}>{t}</PixelButton>)}</div><div className="mt-4 flex flex-wrap gap-2"><PixelButton onClick={toggleSound}>Sound {save.settings.sound ? 'On' : 'Off'}</PixelButton><PixelButton onClick={toggleMotion}>Motion {save.settings.reducedMotion ? 'Reduced' : 'On'}</PixelButton><PixelButton onClick={exportSave}>Export JSON</PixelButton><label className="pixel-border-sm cursor-pointer bg-white px-3 py-2 text-[10px]">Import JSON<input className="hidden" type="file" accept="application/json" onChange={(e) => { const file = e.target.files?.[0]; if (file) void file.text().then(importSave); }} /></label><PixelButton onClick={resetPet} tone="bg-orange-200">Reset Pet</PixelButton><PixelButton onClick={resetAll} tone="bg-red-300">Reset All</PixelButton></div></PixelCard></div>; }
export default function PixelPalsApp() {
  const [save, setSave] = useState<SaveData>(defaultSave());
  const [loaded, setLoaded] = useState(false);
  const [page, setPage] = useState('Pet');
  const [dialog, setDialog] = useState('Selamat datang di Pixel Paws!');
  const [toasts, setToasts] = useState<Toast[]>([]);
  const [dailyOpen, setDailyOpen] = useState(false);
  const [confirm, setConfirm] = useState<null | 'pet' | 'all'>(null);
  const [selectedAnimal, setSelectedAnimal] = useState('cat');
  const [petName, setPetName] = useState('');
  const [shopTab, setShopTab] = useState<ItemCategory>('Food');
  const [game, setGame] = useState<'none'|'catch'|'memory'|'rhythm'>('none');
  const activePet = useMemo(() => save.pets.find((p) => p.id === save.activePetId) ?? null, [save.pets, save.activePetId]);
  const mood = activePet ? getMood(activePet) : 'Senang';
  const themeClass = `theme-${save.settings.theme.replaceAll(' ', '-')}`;
  const notify = useCallback((message: string, type: Toast['type'] = 'info') => { const id = crypto.randomUUID(); setToasts((t) => [...t, { id, message, type }]); setTimeout(() => setToasts((t) => t.filter((x) => x.id !== id)), 2600); }, []);
  const updateSave = useCallback((fn: (s: SaveData) => SaveData) => setSave((prev) => ({ ...fn(prev), lastUpdatedAt: Date.now() })), []);
  const updateActivePet = useCallback((fn: (p: Pet) => Pet) => updateSave((s) => ({ ...s, pets: s.pets.map((p) => p.id === s.activePetId ? fn(p) : p) })), [updateSave]);

  useEffect(() => { setSave(safeParseSave(typeof window !== 'undefined' ? localStorage.getItem(SAVE_KEY) : null)); setLoaded(true); }, []);
  useEffect(() => { if (loaded) localStorage.setItem(SAVE_KEY, JSON.stringify(save)); }, [loaded, save]);
  useEffect(() => { if (!loaded) return; const id = window.setInterval(() => { updateSave((s) => { const pets = s.pets.map((p) => { const bad = p.stats.hunger < 18 || p.stats.cleanliness < 18 || p.stats.energy < 12; return applyStats({ ...p, sickMinutes: bad ? p.sickMinutes + 1 : 0 }, { hunger: -0.35, happiness: -0.15, cleanliness: -0.18, energy: p.isSleeping ? 1.2 : -0.08, health: bad ? -0.35 : 0 }); }); return { ...s, pets, weather: Date.now() - s.weatherUpdatedAt > 180000 ? randomWeather() : s.weather, weatherUpdatedAt: Date.now() - s.weatherUpdatedAt > 180000 ? Date.now() : s.weatherUpdatedAt }; }); }, 6000); return () => window.clearInterval(id); }, [loaded, updateSave]);
  useEffect(() => { if (!activePet) return; const list = dialogs[mood] ?? dialogs.Senang; const id = window.setInterval(() => setDialog(list[Math.floor(Math.random()*list.length)] ?? 'Bip bop!'), 4500); return () => window.clearInterval(id); }, [activePet, mood]);
  useEffect(() => { if (!loaded) return; const newly = getUnlockedAchievements(save); if (!newly.length) return; setSave((s) => ({ ...s, achievements: [...s.achievements, ...newly], userCoins: s.userCoins + newly.reduce((sum, id) => sum + (achievements.find((a) => a.id === id)?.reward ?? 0), 0) })); newly.forEach((id) => notify(`Achievement unlocked! ${achievements.find((a) => a.id === id)?.title ?? id}`, 'success')); }, [loaded, save, notify]);
  useEffect(() => { if (activePet?.stats.hunger !== undefined && activePet.stats.hunger < 18) notify('Pet is hungry!', 'warning'); if (activePet?.stats.energy !== undefined && activePet.stats.energy < 15) notify('Pet needs sleep!', 'warning'); if (activePet?.stats.health !== undefined && activePet.stats.health < 25) notify('Pet feels sick!', 'warning'); }, [activePet?.stats.hunger, activePet?.stats.energy, activePet?.stats.health, notify]);

  const adopt = (animalId = selectedAnimal, name = petName) => { const pet = newPet(animalId, name || getAnimal(animalId).species); updateSave((s) => ({ ...s, pets: [...s.pets, pet], activePetId: pet.id, unlockedAnimals: Array.from(new Set([...s.unlockedAnimals, animalId])) })); setPage('Pet'); notify('Pet adopted!', 'success'); };
  const doAction = (key: string) => { if (!activePet) return; const deltas: Record<string, Partial<Stats>> = { feed:{ hunger:24,happiness:5,energy:-3,xp:8,affection:2 }, play:{ happiness:22,energy:-14,hunger:-8,xp:12,affection:4 }, clean:{ cleanliness:34,health:6,xp:8,affection:3 }, sleep:{ xp:2 }, wake:{ happiness:2 }, medicine:{ health:34,happiness:-5,xp:6 }, pet:{ affection:18,happiness:10,energy:-2,xp:4 }, walk:{ happiness:16,energy:save.weather==='Windy'?-15:-10,hunger:-9,cleanliness:save.weather==='Rainy'?-12:-3,xp:12 }, train:{ xp:28,energy:-22,hunger:-12,happiness:Math.random()>.5?8:-6 }, snack:{ happiness:14,hunger:8,health:activePet.snackCountToday > 2 ? -6 : 0,xp:3 } };
    if (activePet.isSleeping && key !== 'wake') { notify('Pet sedang tidur. Bangunkan dulu!', 'warning'); return; }
    if ((mood === 'Sakit' || mood === 'Very Sick') && ['play','walk','train'].includes(key)) { notify('Pet sakit, aktivitas berat dibatasi.', 'warning'); return; }
    updateActivePet((p) => { const today = todayKey(); const base = key === 'sleep' ? { ...p, isSleeping:true } : key === 'wake' ? { ...p, isSleeping:false } : p; const counted = { ...base, actionCounts:{ ...base.actionCounts, [key]:(base.actionCounts[key] ?? 0)+1 }, snackCountToday: key === 'snack' ? (base.lastSnackDate === today ? base.snackCountToday + 1 : 1) : base.snackCountToday, lastSnackDate: key === 'snack' ? today : base.lastSnackDate }; const levelled = levelPet(applyStats(counted, deltas[key] ?? {})); if (levelled.gained) notify(`Level up! +${levelled.gained}`, 'success'); return levelled.pet; });
    if (key === 'walk' && Math.random() > .55) { const coins = 15 + Math.floor(Math.random()*35); updateSave((s) => ({ ...s, userCoins: s.userCoins + coins })); notify(`Walk menemukan 🪙${coins}!`, 'success'); }
    setDialog((dialogs[mood] ?? dialogs.Senang)[Math.floor(Math.random()*5)] ?? 'Bip!'); };
  const buyItem = (item: ShopItem) => updateSave((s) => { if (s.userCoins < item.price) { notify('Not enough coins!', 'warning'); return s; } notify('Item purchased!', 'success'); return { ...s, userCoins: s.userCoins - item.price, inventory: addInventory(s.inventory, item.id) }; });
  const useItem = (inv: InventoryItem) => { const item = itemById(inv.itemId); if (!item || !activePet) return; if (item.category === 'Food') { updateActivePet((p) => levelPet(applyStats(p, item.statEffects ?? { hunger: 10 })).pet); updateSave((s) => ({ ...s, inventory: s.inventory.map((i) => i.itemId === inv.itemId ? { ...i, quantity: i.quantity - 1 } : i).filter((i) => i.quantity > 0) })); return; } updateActivePet((p) => ({ ...p, equippedAccessory: item.category === 'Accessories' ? item.id : p.equippedAccessory, equippedHabitat: item.category === 'Habitats' ? item.id : p.equippedHabitat, equippedDecorations: item.category === 'Decorations' ? Array.from(new Set([...p.equippedDecorations, item.id])).slice(-3) : p.equippedDecorations })); updateSave((s) => ({ ...s, inventory: s.inventory.map((i) => i.itemId === inv.itemId ? { ...i, equipped:true } : i) })); };
  const reward = (coins: number, xp = 0, happy = 0) => { updateSave((s) => ({ ...s, userCoins: s.userCoins + coins })); if (xp || happy) updateActivePet((p) => levelPet(applyStats(p, { xp, happiness: happy })).pet); notify(`Reward 🪙${coins}${xp ? ` +${xp}XP` : ''}`, 'success'); };
  const claimDaily = () => { const last = save.dailyReward.lastClaimDate; if (last === todayKey()) return; const diff = last ? Math.round((new Date(todayKey()).getTime() - new Date(last).getTime()) / 86400000) : 1; const streak = diff === 1 ? save.dailyReward.streak + 1 : 1; const coins = 50 + Math.min(6, streak-1)*15; updateSave((s) => ({ ...s, userCoins: s.userCoins + coins, dailyReward:{ lastClaimDate: todayKey(), streak } })); notify('Daily reward claimed!', 'success'); setDailyOpen(false); };
  const exportSave = () => { const blob = new Blob([JSON.stringify(save, null, 2)], { type:'application/json' }); const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = 'pixel-pals-save.json'; a.click(); URL.revokeObjectURL(a.href); };
  const importSave = (v: string) => { const parsed = safeParseSave(v); setSave(parsed); notify('Import save berhasil.', 'success'); };

  if (!loaded) return <main className="grid min-h-screen place-items-center bg-[var(--bg)] font-pixel text-xs">Loading save...</main>;
  return <main className={`${themeClass} ${save.settings.reducedMotion ? 'reduced-motion' : ''} min-h-screen bg-[var(--bg)] font-pixel`}><ToastProvider toasts={toasts} />{dailyOpen && <DailyRewardModal save={save} claim={claimDaily} close={() => setDailyOpen(false)} />}{confirm && <ConfirmModal title="Konfirmasi Reset" body="Data yang dipilih akan dihapus dari LocalStorage." onCancel={() => setConfirm(null)} onConfirm={() => { if (confirm === 'all') { setSave(defaultSave()); localStorage.removeItem(SAVE_KEY); } else if (activePet) updateSave((s) => ({ ...s, pets:s.pets.filter((p) => p.id !== activePet.id), activePetId:s.pets.find((p) => p.id !== activePet.id)?.id ?? null })); setConfirm(null); }} />}
    <div className="mx-auto flex max-w-7xl gap-4 p-3 pb-24 md:pb-3"><AppShell page={page} setPage={setPage} coins={save.userCoins} openDaily={() => setDailyOpen(true)} />
      <div className="min-w-0 flex-1">{page === 'Couple' ? <CoupleModePage /> : !activePet ? <AnimalSelect selected={selectedAnimal} setSelected={setSelectedAnimal} name={petName} setName={setPetName} adopt={() => adopt()} /> : game !== 'none' ? <MiniGame game={game} setGame={setGame} reward={reward} /> : page === 'Pet' ? <Dashboard pet={activePet} mood={mood} dialog={dialog} save={save} doAction={doAction} setName={(n) => updateActivePet((p) => ({ ...p, customName:n }))} /> : page === 'Shop' ? <Shop tab={shopTab} setTab={setShopTab} save={save} buy={buyItem} /> : page === 'Inventory' ? <Inventory save={save} useItem={useItem} unequip={(id) => updateSave((s) => ({ ...s, inventory:s.inventory.map((i) => i.itemId === id ? { ...i, equipped:false } : i) }))} /> : page === 'Games' ? <Games setGame={setGame} /> : page === 'Achievements' ? <Achievements save={save} /> : page === 'Dex' ? <Dex save={save} adopt={adopt} setActive={(id) => updateSave((s) => ({ ...s, activePetId:id }))} unlock={(a) => updateSave((s) => s.userCoins >= a.unlockCost ? { ...s, userCoins:s.userCoins-a.unlockCost, unlockedAnimals:[...s.unlockedAnimals,a.id] } : (notify('Not enough coins!', 'warning'), s))} /> : <SettingsPanel save={save} setTheme={(theme) => updateSave((s) => ({ ...s, settings:{ ...s.settings, theme } }))} toggleSound={() => updateSave((s) => ({ ...s, settings:{ ...s.settings, sound:!s.settings.sound } }))} toggleMotion={() => updateSave((s) => ({ ...s, settings:{ ...s.settings, reducedMotion:!s.settings.reducedMotion } }))} exportSave={exportSave} importSave={importSave} resetPet={() => setConfirm('pet')} resetAll={() => setConfirm('all')} />}</div>
    </div><BottomNav page={page} setPage={setPage} /></main>;
}
function AppShell({ page, setPage, coins, openDaily }: { page: string; setPage: (p: string) => void; coins: number; openDaily: () => void }) { const nav = ['Pet','Shop','Inventory','Games','Couple','Achievements','Dex','Settings']; return <aside className="hidden w-56 shrink-0 md:block"><PixelCard className="sticky top-3"><h1 className="mb-2 text-sm leading-relaxed">Pixel Paws</h1><p className="mb-4 text-[10px]">🪙 {coins}</p><div className="grid gap-2">{nav.map((n) => <PixelButton key={n} onClick={() => setPage(n)} tone={page === n ? 'bg-yellow-200' : 'bg-white'}>{n}</PixelButton>)}<PixelButton onClick={openDaily}>Daily</PixelButton></div></PixelCard></aside>; }
function BottomNav({ page, setPage }: { page: string; setPage: (p: string) => void }) { const nav = [['Pet','🐾'],['Shop','🛒'],['Games','🎮'],['Couple','💞'],['Dex','📚'],['Settings','⚙️']]; return <nav className="fixed bottom-0 left-0 right-0 z-30 grid grid-cols-6 gap-1 border-t-4 border-slate-950 bg-white p-2 md:hidden">{nav.map(([n,e]) => <button key={n} onClick={() => setPage(n)} className={`border-2 border-slate-950 p-2 text-[9px] ${page===n?'bg-yellow-200':'bg-[var(--soft)]'}`}>{e}<br />{n}</button>)}</nav>; }
function AnimalSelect({ selected, setSelected, name, setName, adopt }: { selected: string; setSelected: (s: string) => void; name: string; setName: (s: string) => void; adopt: () => void }) { return <div className="grid gap-4"><PixelCard><h1 className="text-lg leading-relaxed">Pixel Paws: 8-Bit Animal Tamagotchi</h1><p className="mt-3 text-[10px] leading-relaxed">Pilih hewan pertama dan beri nama custom. Progress akan tersimpan di LocalStorage.</p><input value={name} onChange={(e) => setName(e.target.value)} placeholder="Nama pet" className="mt-4 w-full border-4 border-slate-950 p-3 text-xs" /><PixelButton onClick={adopt} tone="mt-3 bg-yellow-200">Mulai Adopt</PixelButton></PixelCard><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{animals.slice(0,12).map((a) => <AnimalCard key={a.id} animal={a} unlocked={true} owned={false} onSelect={() => setSelected(a.id)} onUnlock={() => setSelected(a.id)} />)}</div><p className="text-[10px]">Terpilih: {getAnimal(selected).species}</p></div>; }
function Dashboard({ pet, mood, dialog, save, doAction, setName }: { pet: Pet; mood: Mood; dialog: string; save: SaveData; doAction: (k: string) => void; setName: (n: string) => void }) { const animal = getAnimal(pet.animalId); const age = Math.max(1, Math.floor((Date.now() - pet.birthDate)/86400000)+1); const time = getTimeOfDay(); const status = mood === 'Very Sick' ? 'Very Sick - butuh obat' : pet.isSleeping ? 'Sleeping' : 'Active'; return <div className="grid gap-4 xl:grid-cols-[1.1fr_.9fr]"><PixelCard className="text-center"><div className="mb-3 flex flex-wrap items-center justify-between gap-2 text-[10px]"><span>🕹️ Hari {age}</span><span>{time}</span><span>{save.weather}</span><span>🪙 {save.userCoins}</span></div><div className="relative overflow-hidden rounded bg-[var(--soft)] p-4"><WeatherFx weather={save.weather} /><PetSprite pet={pet} mood={mood} reduced={save.settings.reducedMotion} /></div><PetDialog text={`${animal.species}: ${dialog}`} /><div className="mt-4 grid gap-2 text-left sm:grid-cols-2"><input value={pet.customName} onChange={(e) => setName(e.target.value)} className="border-4 border-slate-950 p-2 text-[10px]" /><p className="text-[10px] leading-relaxed">Species: {animal.species}<br />Level {pet.level}/50 · {getEvolution(pet.level)}<br />Mood: {mood}<br />Status: {status}<br />Fav: {animal.favoriteFood}, {animal.favoriteToy}, {animal.favoriteHabitat}</p></div></PixelCard><div className="grid gap-4"><PixelCard><h2 className="mb-3 text-sm">Stats</h2><div className="grid gap-3"><StatBar label="Kenyang" value={pet.stats.hunger} color="bg-orange-400" /><StatBar label="Bahagia" value={pet.stats.happiness} color="bg-pink-400" /><StatBar label="Energi" value={pet.stats.energy} color="bg-blue-400" /><StatBar label="Kebersihan" value={pet.stats.cleanliness} color="bg-cyan-300" /><StatBar label="Kesehatan" value={pet.stats.health} color="bg-green-400" /><StatBar label="Kasih sayang" value={pet.stats.affection} color="bg-red-300" /><StatBar label={`XP / ${xpNeed(pet.level)}`} value={(pet.stats.xp / xpNeed(pet.level))*100} color="bg-purple-400" /></div></PixelCard><ActionPanel pet={pet} mood={mood} doAction={doAction} /></div></div>; }
function WeatherFx({ weather }: { weather: string }) { return <div className="pointer-events-none absolute inset-0 text-xl opacity-50">{weather === 'Rainy' && '╱ ╱ ╱ ╱ ╱ ╱'}{weather === 'Snowy' && '✦  ✧  ✦  ✧'}{weather === 'Sunny' && <span className="absolute right-3 top-3">☀️</span>}{weather === 'Cloudy' && <span className="absolute right-3 top-3">☁️</span>}{weather === 'Windy' && <span className="absolute right-3 top-3">〰️</span>}</div>; }
function ActionPanel({ pet, mood, doAction }: { pet: Pet; mood: Mood; doAction: (k: string) => void }) { return <PixelCard><h2 className="mb-3 text-sm">Care Actions</h2><div className="grid grid-cols-2 gap-2 sm:grid-cols-3">{actions.map(([k,l,e]) => <PixelButton key={k} disabled={(pet.isSleeping && k !== 'wake') || (!pet.isSleeping && k === 'wake') || ((mood === 'Sakit' || mood === 'Very Sick') && ['play','walk','train'].includes(k))} onClick={() => doAction(k)}>{e} {l}</PixelButton>)}</div></PixelCard>; }
function Shop({ tab, setTab, save, buy }: { tab: ItemCategory; setTab: (t: ItemCategory) => void; save: SaveData; buy: (i: ShopItem) => void }) { const items = shopItems.filter((i) => i.category === tab); return <div className="grid gap-4"><PixelCard><h2 className="mb-3 text-sm">Shop · 🪙{save.userCoins}</h2><div className="flex flex-wrap gap-2">{categories.map((c) => <PixelButton key={c} onClick={() => setTab(c)} tone={tab===c?'bg-yellow-200':'bg-white'}>{c}</PixelButton>)}</div></PixelCard><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map((item) => <ShopItemCard key={item.id} item={item} coins={save.userCoins} owned={save.inventory.some((i) => i.itemId === item.id)} buy={() => buy(item)} />)}</div></div>; }
function Inventory({ save, useItem, unequip }: { save: SaveData; useItem: (i: InventoryItem) => void; unequip: (id: string) => void }) { return <div className="grid gap-4"><PixelCard><h2 className="text-sm">Inventory</h2><p className="mt-2 text-[10px]">Gunakan makanan, equip aksesori, habitat, dan dekorasi.</p></PixelCard>{save.inventory.length ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{save.inventory.map((inv) => <InventoryItemCard key={inv.itemId} inv={inv} useItem={() => useItem(inv)} unequip={() => unequip(inv.itemId)} />)}</div> : <PixelCard>Inventory kosong.</PixelCard>}</div>; }
function Achievements({ save }: { save: SaveData }) { return <div className="grid gap-4"><PixelCard><h2 className="text-sm">Achievements</h2><p className="mt-2 text-[10px]">Reward otomatis diklaim satu kali saat syarat terpenuhi.</p></PixelCard><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{achievements.map((a) => <AchievementCard key={a.id} achievement={a} unlocked={save.achievements.includes(a.id)} />)}</div></div>; }
function Dex({ save, adopt, setActive, unlock }: { save: SaveData; adopt: (id: string, name?: string) => void; setActive: (id: string) => void; unlock: (a: Animal) => void }) { return <div className="grid gap-4"><PixelCard><h2 className="text-sm">Animal Dex</h2><p className="mt-2 text-[10px]">Unlocked: {save.unlockedAnimals.length}/12 · Pets: {save.pets.length}</p></PixelCard><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{animals.map((a) => { const ownedPet = save.pets.find((p) => p.animalId === a.id); return <AnimalCard key={a.id} animal={a} unlocked={save.unlockedAnimals.includes(a.id)} owned={!!ownedPet} onSelect={() => ownedPet ? setActive(ownedPet.id) : adopt(a.id, a.species)} onUnlock={() => unlock(a)} />; })}</div></div>; }
function Games({ setGame }: { setGame: (g: 'catch'|'memory'|'rhythm') => void }) { return <div className="grid gap-4 md:grid-cols-3"><MiniGameCard title="Catch the Food" desc="Klik makanan random sebelum timer habis untuk coin." onClick={() => setGame('catch')} /><MiniGameCard title="Memory Match" desc="Cocokkan kartu pixel untuk reward." onClick={() => setGame('memory')} /><MiniGameCard title="Tap Rhythm" desc="Tap urutan tombol untuk XP dan happiness." onClick={() => setGame('rhythm')} /></div>; }
function MiniGame({ game, setGame, reward }: { game: 'catch'|'memory'|'rhythm'; setGame: (g: 'none') => void; reward: (c: number, xp?: number, h?: number) => void }) { const [time, setTime] = useState(25); const [score, setScore] = useState(0); const [pos, setPos] = useState({ left: 40, top: 40 }); const [flipped, setFlipped] = useState<number[]>([]); const cards = ['🐱','🐶','🐰','🐹','🐱','🐶','🐰','🐹']; useEffect(() => { const id = window.setInterval(() => setTime((t) => Math.max(0, t-1)), 1000); return () => window.clearInterval(id); }, []); useEffect(() => { if (time === 0) { reward(score * 5, game === 'rhythm' ? score * 3 : 0, score); setGame('none'); } }, [time, score, reward, game, setGame]); if (game === 'memory') return <PixelCard><h2 className="mb-3 text-sm">Memory Match · {time}s · Score {score}</h2><div className="grid max-w-md grid-cols-4 gap-2">{cards.map((c,i) => <button key={`${c}-${i}`} onClick={() => { if (!flipped.includes(i)) { const next = [...flipped, i]; setFlipped(next); if (next.filter((x) => cards[x] === c).length === 2) setScore((s) => s+2); } }} className="h-20 border-4 border-slate-950 bg-white text-3xl">{flipped.includes(i) ? c : '?'}</button>)}</div><PixelButton onClick={() => setGame('none')} tone="mt-4 bg-white">Back</PixelButton></PixelCard>; if (game === 'rhythm') return <PixelCard><h2 className="mb-3 text-sm">Tap Rhythm · {time}s · Score {score}</h2><div className="grid grid-cols-3 gap-3">{['◀','●','▶'].map((b,i) => <button key={b} onClick={() => setScore((s) => s + (i === score % 3 ? 2 : -1))} className={`h-24 border-4 border-slate-950 text-3xl ${i === score % 3 ? 'bg-yellow-200' : 'bg-white'}`}>{b}</button>)}</div><PixelButton onClick={() => setGame('none')} tone="mt-4 bg-white">Back</PixelButton></PixelCard>; return <PixelCard><h2 className="mb-3 text-sm">Catch the Food · {time}s · Score {score}</h2><div className="relative h-80 border-4 border-slate-950 bg-sky-100"><button className="absolute text-4xl" style={{ left:`${pos.left}%`, top:`${pos.top}%` }} onClick={() => { setScore((s) => s+1); setPos({ left: Math.random()*82, top: Math.random()*72 }); }}>🍎</button></div><PixelButton onClick={() => setGame('none')} tone="mt-4 bg-white">Back</PixelButton></PixelCard>; }
