'use client';
import { useState } from 'react';
import { defaultSave } from '@/lib/gameLogic';
import { SAVE_KEY, createBackup, loadSaveResult, restoreLatestBackup, storeValidatedSave } from '@/src/lib/saveSystem';
const actions = [
  ['Add 1,000 coins', (s: ReturnType<typeof defaultSave>) => ({ ...s, userCoins:s.userCoins + 1000 })],
  ['Reduce active stat', (s: ReturnType<typeof defaultSave>) => ({ ...s, pets:s.pets.map((p) => p.id === s.activePetId ? { ...p, stats:{ ...p.stats, hunger:5 } } : p) })],
  ['Trigger death state', (s: ReturnType<typeof defaultSave>) => ({ ...s, pets:s.pets.map((p) => p.id === s.activePetId ? { ...p, isAlive:false, lifeState:'dead' as const, diedAt:Date.now(), deathReason:'Debug simulation' } : p) })],
  ['Add revive token', (s: ReturnType<typeof defaultSave>) => ({ ...s, inventory:[...s.inventory, { itemId:'special-8', quantity:1 }] })],
  ['Egg hatch ready', (s: ReturnType<typeof defaultSave>) => ({ ...s, eggs:[...(s.eggs ?? []), { id:`debug-egg-${Date.now()}`, parentIds:s.pets.slice(0,2).map((p) => p.id), createdAt:Date.now()-1000, hatchAt:Date.now()-1, rarityChance:.1, inheritedTraits:{}, status:'ready' as const }] })],
  ['Errand complete', (s: ReturnType<typeof defaultSave>) => ({ ...s, activeErrand:{ id:`debug-errand-${Date.now()}`, type:'Forest Scout', startedAt:Date.now()-2000, endsAt:Date.now()-1000, claimed:false, rewardCoins:100 } })],
];
export default function DebugClient() { const [message,setMessage]=useState('Development-only tools. Every action writes a validated local save.'); const apply=(fn:(s:ReturnType<typeof defaultSave>)=>ReturnType<typeof defaultSave>)=>{ const current=loadSaveResult().save; storeValidatedSave(fn(current)); setMessage('Debug action applied. Reload the game to inspect it.'); }; return <main className="min-h-screen bg-lime-100 p-4 font-mono"><div className="mx-auto max-w-3xl border-4 border-black bg-white p-4"><h1 className="text-xl font-bold">Pixel Paws /debug</h1><p className="my-3 text-sm">{message}</p><div className="grid gap-2 sm:grid-cols-2">{actions.map(([label,fn])=><button key={label as string} className="border-2 border-black bg-yellow-100 p-3 text-left" onClick={()=>apply(fn as (s:ReturnType<typeof defaultSave>)=>ReturnType<typeof defaultSave>)}>{label as string}</button>)}<button className="border-2 border-black bg-cyan-100 p-3" onClick={()=>{createBackup(loadSaveResult().save,'manual');setMessage('Manual backup created.');}}>Create backup</button><button className="border-2 border-black bg-cyan-100 p-3" onClick={()=>{setMessage(restoreLatestBackup()?'Backup restored.':'No backup available.');}}>Restore backup</button><button className="border-2 border-black bg-red-100 p-3" onClick={()=>{localStorage.setItem(SAVE_KEY,'{broken');setMessage('Corrupt save generated for recovery testing.');}}>Generate corrupt save</button></div></div></main>; }
